In [1]:
## Import libraries
import pandas as pd
import requests
from zipfile import ZipFile
from remotezip import RemoteZip

In [2]:
#########################

In [3]:
# World Bank WDI 2.12 - Health Systems

## Dataset location: https://www.kaggle.com/danevans/world-bank-wdi-212-health-systems

#file_name = "https://www.kaggle.com/danevans/world-bank-wdi-212-health-systems?select=2.12_Health_systems.csv"

## Read and made a dataframe

systems = pd.read_csv('2.12_Health_systems.csv',sep=',')
systems.head(50)

,Country_Region,Province_State,World_Bank_Name,Health_exp_pct_GDP_2016,Health_exp_public_pct_2016,Health_exp_out_of_pocket_pct_2016,Health_exp_per_capita_USD_2016,per_capita_exp_PPP_2016,External_health_exp_pct_2016,Physicians_per_1000_2009-18,Nurse_midwife_per_1000_2009-18,Specialist_surgical_per_1000_2008-18,Completeness_of_birth_reg_2009-18,Completeness_of_death_reg_2008-16
0,Afghanistan,NaN,Afghanistan,10.2,5.1,77.4,57.2,162.8,17.5,0.3,0.3,0.0,42.3,NaN
1,Albania,NaN,Albania,6.7,41.4,58.0,271.5,759.7,0.7,1.2,3.6,11.6,98.4,53.0
2,Algeria,NaN,Algeria,6.6,67.7,30.9,260.4,998.2,0.0,1.8,2.2,12.1,100.0,NaN
3,Andorra,NaN,Andorra,10.4,49.1,41.7,3834.7,4978.7,NaN,3.3,4.0,83.1,100.0,80.0
4,Angola,NaN,Angola,2.9,44.1,35.2,95.2,185.8,3.6,0.2,1.3,NaN,25.0,NaN
5,Antigua and Barbuda,NaN,Antigua and Barbuda,4.3,60.6,32.2,623.1,976.4,0.0,2.8,3.1,14.0,NaN,79.0
6,Argentina,NaN,Argentina,7.5,74.4,15.8,955.2,1531.0,0.6,4.0,2.6,50.1,100.0,100.0
7,Armenia,NaN,Armenia,9.9,16.5,80.6,358.8,876.9,1.7,2.9,5.6,86.7,99.3,76.0
8,Australia,NaN,Australia,9.3,68.3,18.9,5002.4,4529.9,0.0,3.6,12.7,45.1,100.0,100.0
9,Austria,NaN,Austria,10.4,72.5,18.9,4688.3,5295.2,NaN,5.1,8.2,109.9,100.0,100.0
10,Azerbaijan,NaN,Azerbaijan,6.9,20.0,78.9,268.2,1193.1,0.4,3.4,7.0,67.6,NaN,NaN
11,Bahamas,NaN,"Bahamas, The",6.4,49.9,27.7,1835.2,1435.6,0.4,1.9,3.1,NaN,NaN,93.0
12,Bahrain,NaN,Bahrain,4.9,61.4,28.0,1099.4,1866.3,0.0,0.9,2.5,14.4,NaN,88.0
13,Bangladesh,NaN,Bangladesh,2.4,18.0,71.9,34.2,90.6,7.6,0.5,0.3,2.9,20.2,NaN
14,Barbados,NaN,Barbados,7.0,45.9,45.2,1163.8,1323.0,1.7,2.5,6.0,17.2,99.0,100.0
15,Belarus,NaN,Belarus,6.3,61.4,35.8,318.0,1151.4,0.2,4.1,11.4,124.2,100.0,100.0
16,Belgium,NaN,Belgium,10.0,84.1,15.9,4149.4,4667.9,0.0,3.3,11.1,89.8,100.0,100.0
17,Belize,NaN,Belize,6.1,66.3,22.9,303.6,541.4,3.8,1.1,1.7,10.5,96.0,100.0
18,Benin,NaN,Benin,3.9,20.5,43.5,30.4,83.5,30.5,0.2,0.6,1.9,85.6,NaN
19,Bhutan,NaN,Bhutan,3.5,74.0,20.1,91.3,293.1,4.8,0.4,1.5,2.9,100.0,NaN
20,Bolivia,NaN,Bolivia,6.9,65.7,28.0,213.0,496.3,3.2,1.6,0.7,33.9,92.0,NaN
21,Bosnia and Herzegovina,NaN,Bosnia and Herzegovina,9.2,70.8,28.7,443.8,1123.4,0.2,2.0,6.3,32.3,NaN,89.0
22,Botswana,NaN,Botswana,5.5,55.9,5.2,379.9,931.3,6.7,0.4,3.3,3.6,88.0,NaN
23,Brazil,NaN,Brazil,11.8,33.2,43.6,1015.9,1777.5,0.1,2.1,9.7,55.5,96.0,93.0
24,Brunei,NaN,Brunei Darussalam,2.3,94.9,5.1,630.6,1812.4,0.0,1.8,6.6,NaN,NaN,89.0
25,Bulgaria,NaN,Bulgaria,8.2,50.6,48.0,612.5,1577.9,NaN,4.0,5.3,112.7,100.0,100.0
26,Burkina Faso,NaN,Burkina Faso,6.8,40.1,31.4,40.9,115.6,23.5,0.1,0.6,0.6,76.9,NaN
27,Burundi,NaN,Burundi,6.2,29.1,30.5,18.5,50.3,38.6,0.1,0.7,0.4,83.5,NaN
28,Cabo Verde,NaN,Cabo Verde,5.2,56.8,26.0,159.1,347.6,15.1,0.8,1.2,16.0,91.0,NaN
29,Cambodia,NaN,Cambodia,6.1,21.8,58.6,77.7,228.6,18.9,0.2,1.0,4.2,73.3,NaN
30,Cameroon,NaN,Cameroon,4.7,13.3,69.5,64.5,169.3,9.3,0.1,0.9,1.2,66.0,NaN
31,Canada,NaN,Canada,10.5,73.4,14.6,4458.2,4718.3,NaN,2.6,9.9,43.9,100.0,100.0
32,United Kingdom,Cayman Islands,Cayman Islands,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,156.8,NaN,NaN
33,Central African Republic,NaN,Central African Republic,4.3,14.9,43.1,16.4,29.9,40.9,0.1,0.2,0.4,61.0,NaN
34,Chad,NaN,Chad,4.5,18.9,61.2,31.7,95.0,14.6,0.0,0.4,0.3,12.0,NaN
35,United Kingdom,Channel Islands,Channel Islands,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,38.7,NaN,NaN
36,Chile,NaN,Chile,8.5,58.5,34.8,1190.5,2002.0,0.0,1.1,0.9,59.3,99.0,100.0
37,China,NaN,China,5.0,58.0,35.9,398.3,761.5,0.0,1.8,2.3,40.1,NaN,4.0
38,China,Hong Kong,"Hong Kong SAR, China",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27.8,NaN,NaN
39,China,Macau,"Macao SAR, China",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,Colombia,NaN,Colombia,5.9,62.3,20.2,340.4,829.8,2.1,2.1,1.3,22.7,96.8,98.0
41,Comoros,NaN,Comoros,7.6,14.6,73.1,59.0,115.8,10.8,0.2,0.9,NaN,87.3,NaN
42,Congo (Kinshasa),NaN,"Congo, Dem. Rep.",3.9,12.3,37.4,20.5,34.5,43.4,0.1,0.5,0.2,24.6,NaN
43,Congo (Brazzaville),NaN,"Congo, Rep.",4.6,42.3,49.7,70.4,263.3,3.3,0.1,1.7,0.2,96.0,NaN
44,Costa Rica,NaN,Costa Rica,7.6,74.8,22.1,888.9,1248.5,0.3,1.1,0.8,25.5,100.0,91.0
45,Cote d'Ivoire,NaN,Cote d'Ivoire,4.4,25.8,40.1,67.6,162.6,15.0,0.2,0.9,2.8,72.0,NaN
46,Croatia,NaN,Croatia,7.2,78.2,15.4,884.5,1705.2,NaN,3.0,8.1,81.2,100.0,100.0
47,Cuba,NaN,Cuba,12.2,89.6,10.3,970.6,2457.7,0.1,8.2,7.8,100.9,100.0,98.0
48,Cyprus,NaN,Cyprus,6.9,42.2,44.9,1634.4,2270.8,1.2,2.0,5.3,84.4,100.0,86.0
49,Czechia,NaN,Czech Republic,7.1,81.9,15.0,1321.6,2484.6,NaN,4.3,8.4,124.5,100.0,100.0

In [4]:
systems.columns

Index(['Country_Region', 'Province_State', 'World_Bank_Name',
       'Health_exp_pct_GDP_2016', 'Health_exp_public_pct_2016',
       'Health_exp_out_of_pocket_pct_2016', 'Health_exp_per_capita_USD_2016',
       'per_capita_exp_PPP_2016', 'External_health_exp_pct_2016',
       'Physicians_per_1000_2009-18', 'Nurse_midwife_per_1000_2009-18',
       'Specialist_surgical_per_1000_2008-18',
       'Completeness_of_birth_reg_2009-18',
       'Completeness_of_death_reg_2008-16'],
      dtype='object')

In [5]:
systems = systems.drop(['Country_Region', 'Province_State', 'Completeness_of_birth_reg_2009-18','Completeness_of_death_reg_2008-16'], axis=1)

In [6]:
systems

,World_Bank_Name,Health_exp_pct_GDP_2016,Health_exp_public_pct_2016,Health_exp_out_of_pocket_pct_2016,Health_exp_per_capita_USD_2016,per_capita_exp_PPP_2016,External_health_exp_pct_2016,Physicians_per_1000_2009-18,Nurse_midwife_per_1000_2009-18,Specialist_surgical_per_1000_2008-18
0,Afghanistan,10.2,5.1,77.4,57.2,162.8,17.5,0.3,0.3,0.0
1,Albania,6.7,41.4,58.0,271.5,759.7,0.7,1.2,3.6,11.6
2,Algeria,6.6,67.7,30.9,260.4,998.2,0.0,1.8,2.2,12.1
3,Andorra,10.4,49.1,41.7,3834.7,4978.7,NaN,3.3,4.0,83.1
4,Angola,2.9,44.1,35.2,95.2,185.8,3.6,0.2,1.3,NaN
...,...,...,...,...,...,...,...,...,...,...
205,Virgin Islands (U.S.),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
206,West Bank and Gaza,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
207,"Yemen, Rep.",5.6,10.2,81.0,72.0,144.5,7.8,0.3,0.7,0.8
208,Zambia,4.5,38.3,12.1,56.5,175.2,42.5,0.1,0.9,1.5
209,Zimbabwe,9.4,46.5,21.2,93.9,185.0,25.4,0.1,1.2,1.6

In [7]:
systems.columns = ["Country",
                   "Health_expenditure_(percentage_of_GDP)",
                   "Health_expenditure_(Public_sources)",
                   "Health_expenditure_(Out_pocket_payments)",
                   "Health_expenditure_(per_capita_USD_dollars)",
                   "Health_expenditure_(per_capita_international_dollars)",
                   "Health_expenditure_(External_sources)",
                   "Physicians_per_1000",
                   "Nurses_and_midwives_per_1000",
                   "Specialist_surgical_workforce_per_100000"]

In [8]:
systems

,Country,Health_expenditure_(percentage_of_GDP),Health_expenditure_(Public_sources),Health_expenditure_(Out_pocket_payments),Health_expenditure_(per_capita_USD_dollars),Health_expenditure_(per_capita_international_dollars),Health_expenditure_(External_sources),Physicians_per_1000,Nurses_and_midwives_per_1000,Specialist_surgical_workforce_per_100000
0,Afghanistan,10.2,5.1,77.4,57.2,162.8,17.5,0.3,0.3,0.0
1,Albania,6.7,41.4,58.0,271.5,759.7,0.7,1.2,3.6,11.6
2,Algeria,6.6,67.7,30.9,260.4,998.2,0.0,1.8,2.2,12.1
3,Andorra,10.4,49.1,41.7,3834.7,4978.7,NaN,3.3,4.0,83.1
4,Angola,2.9,44.1,35.2,95.2,185.8,3.6,0.2,1.3,NaN
...,...,...,...,...,...,...,...,...,...,...
205,Virgin Islands (U.S.),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
206,West Bank and Gaza,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
207,"Yemen, Rep.",5.6,10.2,81.0,72.0,144.5,7.8,0.3,0.7,0.8
208,Zambia,4.5,38.3,12.1,56.5,175.2,42.5,0.1,0.9,1.5
209,Zimbabwe,9.4,46.5,21.2,93.9,185.0,25.4,0.1,1.2,1.6

In [9]:
#use the melt and verticalize data 

system_df = pd.melt(systems, id_vars=['Country'])
system_df = system_df.rename(columns={'variable':'parameter', 'value':'value'})
system_df

                    Country                                 parameter  value
0               Afghanistan    Health_expenditure_(percentage_of_GDP)   10.2
1                   Albania    Health_expenditure_(percentage_of_GDP)    6.7
2                   Algeria    Health_expenditure_(percentage_of_GDP)    6.6
3                   Andorra    Health_expenditure_(percentage_of_GDP)   10.4
4                    Angola    Health_expenditure_(percentage_of_GDP)    2.9
...                     ...                                       ...    ...
1885  Virgin Islands (U.S.)  Specialist_surgical_workforce_per_100000    NaN
1886     West Bank and Gaza  Specialist_surgical_workforce_per_100000    NaN
1887            Yemen, Rep.  Specialist_surgical_workforce_per_100000    0.8
1888                 Zambia  Specialist_surgical_workforce_per_100000    1.5
1889               Zimbabwe  Specialist_surgical_workforce_per_100000    1.6

[1890 rows x 3 columns]

In [10]:
names = {
    "Health_expenditure_(percentage_of_GDP)" : '2016',
    "Health_expenditure_(Public_sources)" : '2016',
    "Health_expenditure_(Out_pocket_payments)" : '2016',
    "Health_expenditure_(per_capita_USD_dollars)" : '2016',
    "Health_expenditure_(per_capita_international_dollars)" : '2016',
    "Health_expenditure_(External_sources)" : '2016',
    "Physicians_per_1000" : '2018',
    "Nurses_and_midwives_per_1000" : '2018',
    "Specialist_surgical_workforce_per_100000" : '2018'
}


system_df['Year'] = [names[x] for x in system_df['parameter']]

system_df

,Country,parameter,value,Year
0,Afghanistan,Health_expenditure_(percentage_of_GDP),10.2,2016
1,Albania,Health_expenditure_(percentage_of_GDP),6.7,2016
2,Algeria,Health_expenditure_(percentage_of_GDP),6.6,2016
3,Andorra,Health_expenditure_(percentage_of_GDP),10.4,2016
4,Angola,Health_expenditure_(percentage_of_GDP),2.9,2016
...,...,...,...,...
1885,Virgin Islands (U.S.),Specialist_surgical_workforce_per_100000,NaN,2018
1886,West Bank and Gaza,Specialist_surgical_workforce_per_100000,NaN,2018
1887,"Yemen, Rep.",Specialist_surgical_workforce_per_100000,0.8,2018
1888,Zambia,Specialist_surgical_workforce_per_100000,1.5,2018
1889,Zimbabwe,Specialist_surgical_workforce_per_100000,1.6,2018

In [11]:
#########################

In [12]:
# Efficiency Of Public Spending In Education, Health, And Infrastructure

## Dataset location: https://datacatalog.worldbank.org/dataset/efficiency-public-spending-education-health-and-infrastructure

file_name = "https://development-data-hub-s3-public.s3.amazonaws.com/ddhfiles/144175/paper-final-outpout_0_0.zip"

## First lets see all documents in zipfile

RemoteZip(file_name).namelist()

['Paper Final Outpout/Annex 1 Education/',
 'Paper Final Outpout/Annex 1 Education/Dofiles/',
 'Paper Final Outpout/Annex 1 Education/Dofiles/Single Input-Output/',
 'Paper Final Outpout/Annex 1 Education/Dofiles/Single Input-Output/Excluding developed countries/',
 'Paper Final Outpout/Annex 1 Education/Dofiles/Single Input-Output/Excluding developed countries/Input oriented-excluding developed countries.do',
 'Paper Final Outpout/Annex 1 Education/Dofiles/Single Input-Output/Excluding developed countries/Output oriented-excluding developed countries.do',
 'Paper Final Outpout/Annex 1 Education/Dofiles/Single Input-Output/Including developed countries/',
 'Paper Final Outpout/Annex 1 Education/Dofiles/Single Input-Output/Including developed countries/Input oriented-including developed countries.do',
 'Paper Final Outpout/Annex 1 Education/Dofiles/Single Input-Output/Including developed countries/Output oriented-including developed countries.do',
 'Paper Final Outpout/Annex 1 Education/Dofiles/Two Inputs - One Output/',
 'Paper Final Outpout/Annex 1 Education/Dofiles/Two Inputs - One Output/Excluding developed countries/',
 'Paper Final Outpout/Annex 1 Education/Dofiles/Two Inputs - One Output/Excluding developed countries/Teacher per pupil.do',
 'Paper Final Outpout/Annex 1 Education/Dofiles/Two Inputs - One Output/Input Oriented/',
 'Paper Final Outpout/Annex 1 Education/Dofiles/Two Inputs - One Output/Input Oriented/Adult Literacy rate.do',
 'Paper Final Outpout/Annex 1 Education/Dofiles/Two Inputs - One Output/Input Oriented/Teacher per pupil.do',
 'Paper Final Outpout/Annex 1 Education/Dofiles/Two Inputs - One Output/Output Oriented/',
 'Paper Final Outpout/Annex 1 Education/Dofiles/Two Inputs - One Output/Output Oriented/Adult Literacy rate.do',
 'Paper Final Outpout/Annex 1 Education/Dofiles/Two Inputs - One Output/Output Oriented/Teacher per pupil.do',
 'Paper Final Outpout/Annex 1 Education/Dofiles/Two Inputs - Two Outputs/',
 'Paper Final Outpout/Annex 1 Education/Dofiles/Two Inputs - Two Outputs/Input Teacher per pupil.do',
 'Paper Final Outpout/Annex 1 Education/Dofiles/Two Inputs - Two Outputs/Output Teacher per pupil.do',
 'Paper Final Outpout/Annex 1 Education/Excel files/',
 'Paper Final Outpout/Annex 1 Education/Excel files/Education Results.xlsx',
 'Paper Final Outpout/Annex 1 Education/Word-pdf files/',
 'Paper Final Outpout/Annex 2 Health/',
 'Paper Final Outpout/Annex 2 Health/Private Spending Project/',
 'Paper Final Outpout/Annex 2 Health/Private Spending Project/~$thogonalized and orthogonalized Public and Private Health Spending.docx',
 'Paper Final Outpout/Annex 2 Health/Private Spending Project/Dofile/',
 'Paper Final Outpout/Annex 2 Health/Private Spending Project/Dofile/2x1/',
 'Paper Final Outpout/Annex 2 Health/Private Spending Project/Dofile/2x1/Health 21 Input oriented excluding DC.do',
 'Paper Final Outpout/Annex 2 Health/Private Spending Project/Dofile/2x1/Health 21 Input oriented.do',
 'Paper Final Outpout/Annex 2 Health/Private Spending Project/Dofile/2x1/Health 21 output oriented Excluding.do',
 'Paper Final Outpout/Annex 2 Health/Private Spending Project/Dofile/2x1/Health 21 output oriented.do',
 'Paper Final Outpout/Annex 2 Health/Private Spending Project/Dofile/DEA graphs.do',
 'Paper Final Outpout/Annex 2 Health/Private Spending Project/Dofile/dea.log',
 'Paper Final Outpout/Annex 2 Health/Private Spending Project/Dofile/EDUHEA1.dta',
 'Paper Final Outpout/Annex 2 Health/Private Spending Project/Dofile/Single Input-Output/',
 'Paper Final Outpout/Annex 2 Health/Private Spending Project/Dofile/Single Input-Output/One In-Out Excluding Dev Countries.do',
 'Paper Final Outpout/Annex 2 Health/Private Spending Project/Dofile/Single Input-Output/One In-Out Oriented.do',
 'Paper Final Outpout/Annex 2 Health/Private Spending Project/Excel/',
 'Paper Final Outpout/Annex 2 Health/Private Spending Project/Excel/Private-Results.xlsx',
 'Paper Final Outpout/Annex 2 Health/Private Spending Project/Word/',
 'Paper Final Outpout/Annex 2 Health/Private Spending Project/Word/Efficiency scores results.docx',
 'Paper Final Outpout/Annex 2 Health/Private Spending Project/Word/Health FDH-DEA Graphs.docx',
 'Paper Final Outpout/Annex 2 Health/Private Spending Project/Word/Orthogonalized and orthogonalized Public and Private Health Spending.docx',
 'Paper Final Outpout/Annex 2 Health/Private Spending Project/Word/Private Spending Graphs.docx',
 'Paper Final Outpout/Annex 2 Health/Public Spending/',
 'Paper Final Outpout/Annex 2 Health/Public Spending/Dofile/',
 'Paper Final Outpout/Annex 2 Health/Public Spending/Dofile/2x1/',
 'Paper Final Outpout/Annex 2 Health/Public Spending/Dofile/2x1/21 Inputds-Ensecgro.do',
 'Paper Final Outpout/Annex 2 Health/Public Spending/Dofile/2x1/21 Inputds-ImpSanitation.do',
 'Paper Final Outpout/Annex 2 Health/Public Spending/Dofile/2x1/21 Inputds-litadult.do',
 'Paper Final Outpout/Annex 2 Health/Public Spending/Dofile/2x1/21 outputds-Ensecgro.do',
 'Paper Final Outpout/Annex 2 Health/Public Spending/Dofile/2x1/21 outputds-ImpSanitation.do',
 'Paper Final Outpout/Annex 2 Health/Public Spending/Dofile/2x1/21 outputds-litadult.do',
 'Paper Final Outpout/Annex 2 Health/Public Spending/Dofile/2x1/22 Input PS Net Sec.do',
 'Paper Final Outpout/Annex 2 Health/Public Spending/Dofile/2x1/22 Output PS Net Sec.do',
 'Paper Final Outpout/Annex 2 Health/Public Spending/Dofile/2x1/dea.log',
 'Paper Final Outpout/Annex 2 Health/Public Spending/Dofile/2x2/',
 'Paper Final Outpout/Annex 2 Health/Public Spending/Dofile/2x2/2 input-output Input oriented efficiency excluding.do',
 'Paper Final Outpout/Annex 2 Health/Public Spending/Dofile/2x2/2 input-output Input oriented efficiency Including.do',
 'Paper Final Outpout/Annex 2 Health/Public Spending/Dofile/2x2/2 input-output Output oriented efficiency excluding.do',
 'Paper Final Outpout/Annex 2 Health/Public Spending/Dofile/2x2/2 input-output Output oriented efficiency including.do',
 'Paper Final Outpout/Annex 2 Health/Public Spending/Dofile/2x2/22 Input literacy Incl.do',
 'Paper Final Outpout/Annex 2 Health/Public Spending/Dofile/2x2/22 Input Priv-Pub Incl.do',
 'Paper Final Outpout/Annex 2 Health/Public Spending/Dofile/2x2/22 output literacy Incl.do',
 'Paper Final Outpout/Annex 2 Health/Public Spending/Dofile/2x2/22 Output Priv-Pub Incl.do',
 'Paper Final Outpout/Annex 2 Health/Public Spending/Dofile/2x2/dea.log',
 'Paper Final Outpout/Annex 2 Health/Public Spending/Dofile/2x2/Health 2inputs & 2out out revised excl.do',
 'Paper Final Outpout/Annex 2 Health/Public Spending/Dofile/2x2/Health 2inputs & 2outputs Inp revised excl.do',
 'Paper Final Outpout/Annex 2 Health/Public Spending/Dofile/Single Input-output/',
 'Paper Final Outpout/Annex 2 Health/Public Spending/Dofile/Single Input-output/Input/',
 'Paper Final Outpout/Annex 2 Health/Public Spending/Dofile/Single Input-output/Input/dea.log',
 'Paper Final Outpout/Annex 2 Health/Public Spending/Dofile/Single Input-output/Input/input incl dev.do',
 'Paper Final Outpout/Annex 2 Health/Public Spending/Dofile/Single Input-output/Output/',
 'Paper Final Outpout/Annex 2 Health/Public Spending/Dofile/Single Input-output/Output/dea.log',
 'Paper Final Outpout/Annex 2 Health/Public Spending/Dofile/Single Input-output/Output/Output oriented-excluding developed countries.do',
 'Paper Final Outpout/Annex 2 Health/Public Spending/Dofile/Single Input-output/Output/Output oriented-including developed countries.do',
 'Paper Final Outpout/Annex 2 Health/Public Spending/Dofile/Single Input-output/Survival dofile.do',
 'Paper Final Outpout/Annex 2 Health/Public Spending/Excel/',
 'Paper Final Outpout/Annex 2 Health/Public Spending/Excel/Health Single In-out Results.xlsx',
 'Paper Final Outpout/Annex 2 Health/Public Spending/Word/',
 'Paper Final Outpout/Annex 2 Health/Public Spending/Word/Efficiency scores by regions Excluding Dev countries.docx',
 'Paper Final Outpout/Annex 2 Health/Public Spending/Word/Graphs Efficiency  FDH-DEA.docx',
 'Paper Final Outpout/Annex 2 Health/Public Spending/Word/Health Efficiency Scores Single In-Out.docx',
 'Paper Final Outpout/Annex 2 Health/Public Spending/Word/Linear Graphs (TTO).docx',
 'Paper Final Outpout/Annex 3 Infrastructure/',
 'Paper Final Outpout/Annex 3 Infrastructure/Dofiles/',
 'Paper Final Outpout/Annex 3 Infrastructure/Dofiles/2x1/',
 'Paper Final Outpout/Annex 3 Infrastructure/Dofiles/2x1/21 Input Excl Dev Countries.do',
 'Paper Final Outpout/Annex 3 Infrastructure/Dofiles/2x1/21 Input.do',
 'Paper Final Outpout/Annex 3 Infrastructure/Dofiles/2x1/21 Output Excl Dev Countries.do',
 'Paper Final Outpout/Annex 3 Infrastructure/Dofiles/2x1/21 Output.do',
 'Paper Final Outpout/Annex 3 Infrastructure/Dofiles/2x1/DEA Graphs.do',
 'Paper Final Outpout/Annex 3 Infrastructure/Dofiles/Other/',
 'Paper Final Outpout/Annex 3 Infrastructure/Dofiles/Other/Linear.do',
 'Paper Final Outpout/Annex 3 Infrastructure/Dofiles/Other/Managing dofile.do',
 'Paper Final Outpout/Annex 3 Infrastructure/Dofiles/Other/Tobit.do',
 'Paper Final Outpout/Annex 3 Infrastructure/Dofiles/Single Input-Output/',
 'Paper Final Outpout/Annex 3 Infrastructure/Dofiles/Single Input-Output/Private/',
 'Paper Final Outpout/Annex 3 Infrastructure/Dofiles/Single Input-Output/Private/DEA Private Graphs.do',
 'Paper Final Outpout/Annex 3 Infrastructure/Dofiles/Single Input-Output/Private/Input oriented Private Excl.do',
 'Paper Final Outpout/Annex 3 Infrastructure/Dofiles/Single Input-Output/Private/Input oriented Private Inv.do',
 'Paper Final Outpout/Annex 3 Infrastructure/Dofiles/Single Input-Output/Private/Output oriented Private Excl.do',
 'Paper Final Outpout/Annex 3 Infrastructure/Dofiles/Single Input-Output/Private/Output oriented Private Inv.do',
 'Paper Final Outpout/Annex 3 Infrastructure/Dofiles/Single Input-Output/Public/',
 'Paper Final Outpout/Annex 3 Infrastructure/Dofiles/Single Input-Output/Public/dea.log',
 'Paper Final Outpout/Annex 3 Infrastructure/Dofiles/Single Input-Output/Public/Input oriented Public Excl dc.do',
 'Paper Final Outpout/Annex 3 Infrastructure/Dofiles/Single Input-Output/Public/Input oriented Public Inv.do',
 'Paper Final Outpout/Annex 3 Infrastructure/Dofiles/Single Input-Output/Public/Output oriented Public Excl dc.do',
 'Paper Final Outpout/Annex 3 Infrastructure/Dofiles/Single Input-Output/Public/Output oriented Public Inv.do',
 'Paper Final Outpout/Annex 3 Infrastructure/Dofiles/Single Input-Output/Public/Private to Public.do',
 'Paper Final Outpout/Annex 3 Infrastructure/Excel files/',
 'Paper Final Outpout/Annex 3 Infrastructure/Excel files/~$Including Dev Countries results.xlsx',
 'Paper Final Outpout/Annex 3 Infrastructure/Excel files/Results.xlsx',
 'Paper Final Outpout/Annex 3 Infrastructure/Input/',
 'Paper Final Outpout/Annex 3 Infrastructure/Input/Collapsed full data.dta',
 'Paper Final Outpout/Annex 3 Infrastructure/Input/Data for spearman correlation.dta',
 'Paper Final Outpout/Annex 3 Infrastructure/Input/dea.log',
 'Paper Final Outpout/Annex 3 Infrastructure/Input/Tobit Regression.dta',
 'Paper Final Outpout/Annex 3 Infrastructure/Input/weo gfcf data.dta',
 'Paper Final Outpout/Annex 3 Infrastructure/Results/',
 'Paper Final Outpout/Annex 3 Infrastructure/Results/Efficiency Scores Public-Private.docx',
 'Paper Final Outpout/Annex 3 Infrastructure/Results/FDH-DEA Private Graphs.docx',
 'Paper Final Outpout/Annex 3 Infrastructure/Results/FDH-DEA Public Graphs.docx',
 'Paper Final Outpout/Annex 3 Infrastructure/Results/Linear Graphs.docx',
 'Paper Final Outpout/Annex 3 Infrastructure/Results/Orthogonalized Public and Private Investment graphs.docx',
 'Paper Final Outpout/Annex 4 Excel dofiles/',
 'Paper Final Outpout/Annex 4 Excel dofiles/DEA-FDH scores.xlsx',
 'Paper Final Outpout/Annex 4 Excel dofiles/FDH-DEAMultipleInputOrientation.do',
 'Paper Final Outpout/Annex 4 Excel dofiles/FDH-DEAMultipleOutputOrientation.do',
 'Paper Final Outpout/Annex 4 Excel dofiles/FDH-DEASingleInputOrientation.do',
 'Paper Final Outpout/Annex 4 Excel dofiles/FDH-DEASingleOutputOrientation.do',
 'Paper Final Outpout/Annex 4 Excel dofiles/Working Dataset.xlsx',
 'Paper Final Outpout/Annex 5 Data and Scores/']

In [13]:
## Lets choose which data we need

file = RemoteZip(file_name).open('Paper Final Outpout/Annex 4 Excel dofiles/Working Dataset.xlsx').read()

## Read and made a dataframe

efficiency = pd.read_excel(file, sheet_name='Full Dataset')
efficiency.head(50)

,code,Region,Country name,Year,Income group classification,Gross Primary School enrollment,Gross Secondary School enrollment,Net Primary School enrollment,Net Secondary School enrollment,Literacy of Youth,...,Compensation of employees (% of expense) [GC.XPN.COMP.ZS],General government final consumption expenditure (% of GDP) [NE.CON.GOVT.ZS],"Health expenditure, public (% of government expenditure) [SH.XPD.PUBL.GX.ZS]",Unnamed: 84,Control of Corruption: Estimate [CC.EST],Government Effectiveness: Estimate [GE.EST],Political Stability and Absence of Violence/Terrorism: Estimate [PV.EST],Regulatory Quality: Estimate [RQ.EST],Rule of Law: Estimate [RL.EST],Voice and Accountability: Estimate [VA.EST]
0,code,region,country,year,igroup,enprimgro,ensecgro,enprimnet,ensecnet,lityouth,...,compensation_exppur,govexpgdp,healthpubshare,hivaids,corruption,govereffectiveness,polstability_noviolence,quality,ruleoflaw,voiceandaccountabilityestimateva
1,AGO,AFR,Angola,2006,Lower middle income,NaN,NaN,NaN,NaN,NaN,...,38.695679,18.451524,9.564669,1,-1.22006,-1.36949,-0.54,-1.13291,-1.30031,-1.25209
2,AGO,AFR,Angola,2007,Lower middle income,105.21,NaN,NaN,NaN,NaN,...,34.956402,15.277774,6.416707,1,-1.28969,-1.20641,-0.67,-1.02466,-1.3659,-1.18531
3,AGO,AFR,Angola,2008,Lower middle income,111.914,10.1277,80.1991,23.5546,NaN,...,36.509633,17.132234,6.464507,1,-1.28462,-1.06221,-0.36,-1.06534,-1.36698,-1.11935
4,AGO,AFR,Angola,2009,Lower middle income,111.158,10.606,79.6908,24.9925,NaN,...,46.747196,17.504707,6.358449,1,-1.40465,-0.960353,-0.35,-1.03147,-1.23084,-1.12612
5,AGO,AFR,Angola,2010,Lower middle income,113.508,12.3751,81.3394,28.7813,NaN,...,36.137156,17.658536,5.432331,1,-1.32573,-1.1179,-0.23,-1.03593,-1.26529,-1.12054
6,AGO,AFR,Angola,2011,Lower middle income,128.704,NaN,84.0123,28.8987,NaN,...,31.324936,19.573321,5.584801,1,-1.34429,-1.15356,-0.37,-1.09778,-1.26538,-1.12548
7,AGO,AFR,Angola,2012,Lower middle income,NaN,NaN,NaN,NaN,NaN,...,35.939206,21.218211,5.573031,1,-1.26859,-0.989632,-0.39,-0.969778,-1.26955,-1.07625
8,AGO,AFR,Angola,2013,Lower middle income,NaN,NaN,NaN,NaN,NaN,...,31.025385,19.79045,7.423221,1,-1.3097,-1.22317,-0.39,-1.05422,-1.2679,-1.11384
9,AGO,AFR,Angola,2014,Lower middle income,NaN,NaN,NaN,NaN,77.4311,...,32.923122,20.595225,5.004294,1,-1.44389,-1.12367,-0.33,-0.988459,-1.11814,-1.14549
10,AGO,AFR,Angola,2015,Lower middle income,NaN,NaN,NaN,NaN,NaN,...,47.860634,17.669885,NaN,1,-1.39475,-1.00009,-0.5,-0.909186,-1.08193,-1.17719
11,AGO,AFR,Angola,2016,Lower middle income,NaN,NaN,NaN,NaN,NaN,...,NaN,12.888163,NaN,1,-1.41183,-1.03938,-0.39,-1.00138,-1.08052,-1.16736
12,ALB,ECA,Albania,2006,Upper middle income,99.5938,NaN,NaN,77.9559,NaN,...,NaN,10.134929,9.040574,0,-0.803845,-0.523602,-0.51,-0.10176,-0.684769,0.07589
13,ALB,ECA,Albania,2007,Upper middle income,99.0931,NaN,NaN,81.2809,NaN,...,NaN,10.163764,8.880175,0,-0.687789,-0.406624,-0.2,0.060612,-0.646296,0.113008
14,ALB,ECA,Albania,2008,Upper middle income,99.5195,NaN,90.2673,83.6489,98.8312,...,NaN,10.378957,8.365607,0,-0.593707,-0.356764,-0.03,0.14754,-0.588695,0.174939
15,ALB,ECA,Albania,2009,Upper middle income,97.5253,NaN,89.3933,85.4093,NaN,...,NaN,11.10943,8.463262,0,-0.538495,-0.257898,-0.05,0.238284,-0.50043,0.141477
16,ALB,ECA,Albania,2010,Upper middle income,99.0133,NaN,91.0339,88.4116,NaN,...,NaN,11.157364,8.463262,0,-0.525078,-0.282755,-0.19,0.229477,-0.407376,0.123822
17,ALB,ECA,Albania,2011,Upper middle income,101.816,NaN,93.2257,90.8484,98.7912,...,26.606184,10.974165,9.850791,0,-0.683008,-0.208207,-0.28,0.232936,-0.455371,0.062334
18,ALB,ECA,Albania,2012,Upper middle income,104.784,NaN,96.1371,92.7415,99.2314,...,26.878819,10.844816,9.710531,0,-0.726501,-0.2678,-0.14,0.199169,-0.520316,0.022064
19,ALB,ECA,Albania,2013,Upper middle income,107.785,84.0238,95.5457,95.8316,NaN,...,25.592943,11.025496,9.762421,0,-0.698603,-0.31692,0.09,0.209719,-0.518018,0.048893
20,ALB,ECA,Albania,2014,Upper middle income,112.487,85.2782,95.5173,96.4261,NaN,...,24.871308,11.451836,9.369005,0,-0.548199,-0.085558,0.49,0.22199,-0.337862,0.143761
21,ALB,ECA,Albania,2015,Upper middle income,113.7,85.9145,NaN,95.7655,NaN,...,24.470754,11.161305,NaN,0,-0.479021,0.010404,0.35,0.186668,-0.328226,0.15713
22,ALB,ECA,Albania,2016,Upper middle income,NaN,NaN,NaN,NaN,NaN,...,23.064615,11.134098,NaN,0,-0.397567,-0.000573,0.26,0.188962,-0.347468,0.159191
23,ARE,MNA,United Arab Emirates,2006,High income,104.057,NaN,88.2077,NaN,NaN,...,NaN,6.917789,8.846775,0,0.893287,0.943855,0.92,0.625478,0.31992,-0.999829
24,ARE,MNA,United Arab Emirates,2007,High income,103.091,NaN,87.9464,NaN,NaN,...,NaN,6.733024,8.810033,0,1.01352,0.923829,0.98,0.609858,0.285038,-0.906883
25,ARE,MNA,United Arab Emirates,2008,High income,NaN,NaN,NaN,NaN,NaN,...,NaN,7.29686,8.754612,0,1.08244,0.876649,0.7,0.567346,0.424308,-0.912381
26,ARE,MNA,United Arab Emirates,2009,High income,97.3292,NaN,82.8186,NaN,NaN,...,NaN,10.23409,8.669691,0,0.912934,0.990985,0.92,0.444514,0.404846,-0.838312
27,ARE,MNA,United Arab Emirates,2010,High income,99.6996,NaN,85.452,NaN,NaN,...,NaN,10.02785,8.679952,0,0.896254,0.897961,0.8,0.320225,0.32302,-0.903513
28,ARE,MNA,United Arab Emirates,2011,High income,99.0845,NaN,85.5894,NaN,NaN,...,29.66687,9.94644,8.685756,0,1.07753,1.05526,0.91,0.449241,0.504776,-0.896244
29,ARE,MNA,United Arab Emirates,2012,High income,101.423,NaN,87.8147,NaN,NaN,...,31.086027,9.724537,8.697356,0,1.16352,1.14961,0.86,0.676252,0.53951,-1.00082
30,ARE,MNA,United Arab Emirates,2013,High income,100.974,NaN,87.5571,NaN,NaN,...,32.226993,11.426802,8.696859,0,1.28084,1.17637,0.89,0.780733,0.619024,-1.01948
31,ARE,MNA,United Arab Emirates,2014,High income,106.712,NaN,90.7382,NaN,NaN,...,34.267317,11.644284,8.691676,0,1.20358,1.43552,0.77,0.992054,0.652227,-1.06137
32,ARE,MNA,United Arab Emirates,2015,High income,116.346,NaN,93.375,NaN,NaN,...,36.669845,13.616788,NaN,0,1.07192,1.50987,0.76,1.11106,0.640877,-1.11237
33,ARE,MNA,United Arab Emirates,2016,High income,NaN,NaN,NaN,NaN,NaN,...,34.82428,14.030736,NaN,0,1.27617,1.41364,0.44,0.972667,0.887417,-1.12215
34,ARG,LAC,Argentina,2006,Upper middle income,118.835,79.1071,98.8024,93.3451,NaN,...,NaN,12.429415,16.350931,0,-0.341254,-0.045504,0,-0.640632,-0.568944,0.403437
35,ARG,LAC,Argentina,2007,Upper middle income,119.349,79.1983,99.0615,93.7067,NaN,...,NaN,12.989324,15.36737,0,-0.340292,-0.015959,0.1,-0.668216,-0.591604,0.448621
36,ARG,LAC,Argentina,2008,Upper middle income,119.441,80.348,99.0487,95.2463,NaN,...,NaN,13.633513,15.794894,0,-0.435577,-0.146812,-0.09,-0.73752,-0.676608,0.358896
37,ARG,LAC,Argentina,2009,Upper middle income,118.211,82.409,99.0204,98.8308,NaN,...,NaN,15.903897,17.127231,0,-0.444996,-0.318265,-0.23,-0.845036,-0.675478,0.280048
38,ARG,LAC,Argentina,2010,Upper middle income,116.718,83.9968,98.6673,101.801,NaN,...,NaN,15.163718,14.073398,0,-0.361469,-0.16279,-0.08,-0.762369,-0.590509,0.361689
39,ARG,LAC,Argentina,2011,Upper middle income,114.768,85.2216,98.8426,103.6,NaN,...,NaN,15.688957,11.815001,0,-0.366158,-0.120056,0.16,-0.72221,-0.560893,0.344942
40,ARG,LAC,Argentina,2012,Upper middle income,112.978,87.3181,98.9681,105.193,NaN,...,NaN,16.645438,8.741289,0,-0.44314,-0.238575,0.1,-0.929217,-0.679681,0.29521
41,ARG,LAC,Argentina,2013,Upper middle income,110.566,88.1603,99.0224,106.323,NaN,...,NaN,16.806238,7.723046,0,-0.432282,-0.277549,0.07,-0.957261,-0.707676,0.276988
42,ARG,LAC,Argentina,2014,Upper middle income,109.989,88.246,99.3468,106.778,NaN,...,12.872711,16.949876,6.916974,0,-0.54162,-0.159135,-0.01,-1.07426,-0.886035,0.345321
43,ARG,LAC,Argentina,2015,Upper middle income,NaN,NaN,NaN,NaN,99.3,...,13.168382,18.496921,NaN,0,-0.547045,-0.074903,0.01,-0.911442,-0.770812,0.411753
44,ARG,LAC,Argentina,2016,Upper middle income,NaN,NaN,NaN,NaN,NaN,...,12.12885,18.432221,NaN,0,-0.313136,0.176796,0.22,-0.46968,-0.345988,0.540847
45,ARM,ECA,Armenia,2006,Lower middle income,97.7113,87.9384,81.4127,93.8858,NaN,...,21.297322,10.090269,11.331764,0,-0.670823,-0.254579,-0.26,0.284606,-0.546435,-0.742223
46,ARM,ECA,Armenia,2007,Lower middle income,108.467,90.158,84.1356,94.873,NaN,...,21.365911,10.173184,10.416327,0,-0.742384,-0.375844,0.15,0.271804,-0.498376,-0.759378
47,ARM,ECA,Armenia,2008,Lower middle income,107.554,84.055,NaN,92.7056,NaN,...,21.011127,10.229205,7.003086,0,-0.708098,-0.172694,-0.01,0.337868,-0.340527,-0.85763
48,ARM,ECA,Armenia,2009,Lower middle income,102.449,89.1006,NaN,96.6329,NaN,...,24.799314,13.336621,6.719882,0,-0.619758,-0.029735,0.23,0.296256,-0.475852,-0.876475
49,ARM,ECA,Armenia,2010,Lower middle income,NaN,NaN,NaN,NaN,NaN,...,23.595311,13.070948,6.967334,0,-0.696304,-0.183844,0.07,0.309482,-0.48864,-0.847555

In [14]:
## Lets clean the dataframe

## see column names
efficiency.columns

## select columns not related to drop
columns_drop = ['Gross Primary School enrollment', 'Gross Secondary School enrollment', 'Net Primary School enrollment',
                'Net Secondary School enrollment', 'Literacy of Youth', 'Literacy of Adult',
                'first level complete (% of population ages 15+)','second level complete (% of population ages 15+)',
                'average years of school (ages 15+)', 'teacher per Pupils', 'Pupils per teacher',
                'Quality of primary education, 1-7 (best)', 'Primary education Net Enrollment, net %',
                'Secondary Education Gross Enrollment, gross %', 'Tertiary education enrollment, gross %',
                'Quality of the education system, 1-7 (best)', 'Quality of math and science education, 1-7 (best)',
                'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'PISA Reading scores', 'PISA Science scores',
                'PISA Mathematics scores', 'Population using improved drinking-water sources (%)',
                'Population using improved sanitation facilities (%)', 'GDP per capita, constant 2011 international $',
                'Public spending on Education (% of GDP) ', 'Public Spending on Education per capita, PPP $',
                'Quality of overall infrastructure, 1-7 (best)', 'Quality of roads, 1-7 (best)',
                'Quality of railroad infrastructure, 1-7 (best)', 'Quality of port infrastructure, 1-7 (best)',
                'Quality of air transport infrastructure, 1-7 (best)', 'A. Transport infrastructure',
                'Quality of electricity supply, 1-7 (best)', 'B. Electricity and telephony infrastructure',
                '2nd pillar: Infrastructure', 'A. Technological adoption', 'Innovation and sophistication factors',
                'GDP per capita (constant 2010 US$) [NY.GDP.MKTP.KD]', 'GDP (constant 2010 US$) [NY.GDP.MKTP.KD]',
                'GDP (current US$) [NY.GDP.MKTP.CD]',
                'National Currency per PPP dollar (Units National Currency per PPP dollar) [PPPEX]',
                'Private gross fixed capital formation, current prices (Billions National Currency) [NFIP]',
                'Public gross fixed capital formation, current prices (Billions National Currency) [NFIG]',
                'Population (Millions Persons) [LP]', 'Public investment spending per capita',
                'Private investment spending per capita', 'Total investment spending per capita',
                'GDP per capita, PPP (constant 2011 international $) [NY.GDP.PCAP.PP.KD]',
                'Government expenditure on education, total (% of GDP) [SE.XPD.TOTL.GD.ZS]',
                'Urban population (% of total) [SP.URB.TOTL.IN.ZS]', 'GINI index (World Bank estimate) [SI.POV.GINI]',
                'Net official development assistance and official aid received (current US$) [DT.ODA.ALLD.CD]',
                'Official exchange rate (LCU per US$, period average) [PA.NUS.FCRF]',
                'Net official development assistance and official aid received (constant 2013 US$) [DT.ODA.ALLD.KD]',
                'Revenue, excluding grants (current LCU) [GC.REV.XGRT.CN]',
                'PPP conversion factor, GDP (LCU per international $) [PA.NUS.PPP]',
                'Current education expenditure, total (% of total expenditure in public institutions) [SE.XPD.CTOT.ZS]',
                'Government expenditure on education, total (% of government expenditure) [SE.XPD.TOTL.GB.ZS]',
                'Compensation of employees (% of expense) [GC.XPN.COMP.ZS]',
                'General government final consumption expenditure (% of GDP) [NE.CON.GOVT.ZS]', 'Unnamed: 84',
                'Control of Corruption: Estimate [CC.EST]', 'Government Effectiveness: Estimate [GE.EST]',
                'Political Stability and Absence of Violence/Terrorism: Estimate [PV.EST]',
                'Regulatory Quality: Estimate [RQ.EST]', 'Rule of Law: Estimate [RL.EST]', 
                'Voice and Accountability: Estimate [VA.EST]']
    
efficiency = efficiency.drop(columns=columns_drop)  
efficiency

,code,Region,Country name,Year,Income group classification,Life expectancy at birth,Immunization DPT,Immunization Measles,Disability Adjusted Life Exectancy,Maternal Survival Rate,...,Private spending on health (% of GDP),Public spending on health (% of GDP),Total spending on health (% of GDP),"Public Spending on health per capita, PPP $","Private Spending on health per capita, PPP $","Total Spending on health per capita, PPP $","Health expenditure, private (% of GDP) [SH.XPD.PRIV.ZS]","Health expenditure, public (% of GDP) [SH.XPD.PUBL.ZS]","Health expenditure per capita, PPP (constant 2011 international $) [SH.XPD.PCAP.PP.KD]","Health expenditure, public (% of government expenditure) [SH.XPD.PUBL.GX.ZS]"
0,code,region,country,year,igroup,lifebirth,imdpt,immea,dale,matmortalityrat,...,hprivgdp,hpubgdp,htotGDP,heappp,privheappp,htotppp,healthexp_private,helathexp_pub,pchealthexp_11cons,healthpubshare
1,AGO,AFR,Angola,2006,Lower middle income,53.9271,34,33,56.89,NaN,...,0.0152,0.030224,0.045424,139.0657,69.93706,209.0028,1.520002,3.022435,209.61484,9.564669
2,AGO,AFR,Angola,2007,Lower middle income,55.0475,73,71,NaN,NaN,...,0.011694,0.022138,0.033831,120.498,63.64907,184.147,1.169348,2.213764,189.90187,6.416707
3,AGO,AFR,Angola,2008,Lower middle income,56.1393,69,61,NaN,NaN,...,0.011286,0.027163,0.038449,162.3916,67.47146,229.863,1.128599,2.716334,242.15426,6.464507
4,AGO,AFR,Angola,2009,Lower middle income,57.181,60,57,NaN,NaN,...,0.017079,0.026639,0.043718,157.3856,100.9011,258.2867,1.707857,2.663917,274.73451,6.358449
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1932,ZWE,AFR,Zimbabwe,2012,Low income,56.4077,95,97,NaN,NaN,...,0.039146,0.027716,0.066862,51.2249,72.3487,123.5736,3.914563,2.77162,112.2178,9.691281
1933,ZWE,AFR,Zimbabwe,2013,Low income,57.9405,95,93,NaN,NaN,...,0.040314,0.028474,0.068788,54.13524,76.64409,130.7793,4.031388,2.84745,119.73334,9.593592
1934,ZWE,AFR,Zimbabwe,2014,Low income,59.2443,91,92,NaN,NaN,...,0.03973,0.024665,0.064395,47.07251,75.82336,122.8959,3.972976,2.466495,114.60851,8.486653
1935,ZWE,AFR,Zimbabwe,2015,Low income,60.2793,87,86,NaN,0.99557,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1936,ZWE,AFR,Zimbabwe,2016,Low income,NaN,90,95,59.2,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
efficiency.columns

Index(['code', 'Region', 'Country name', 'Year', 'Income group classification',
       'Life expectancy at birth', 'Immunization DPT', 'Immunization Measles',
       'Disability Adjusted Life Exectancy', 'Maternal Survival Rate',
       'Infant Survival Rate', 'Free Tuberculosis cases rate',
       'Private spending on health (% of GDP)',
       'Public spending on health (% of GDP)',
       'Total spending on health (% of GDP)',
       'Public Spending on health per capita, PPP $',
       'Private Spending on health per capita, PPP $',
       'Total Spending on health per capita, PPP $',
       'Health expenditure, private (% of GDP) [SH.XPD.PRIV.ZS]',
       'Health expenditure, public (% of GDP) [SH.XPD.PUBL.ZS]',
       'Health expenditure per capita, PPP (constant 2011 international $) [SH.XPD.PCAP.PP.KD]',
       'Health expenditure, public (% of government expenditure) [SH.XPD.PUBL.GX.ZS]'],
      dtype='object')

In [16]:
efficiency = efficiency.drop(['code','Region'], axis=1)

In [17]:
efficiency

,Country name,Year,Income group classification,Life expectancy at birth,Immunization DPT,Immunization Measles,Disability Adjusted Life Exectancy,Maternal Survival Rate,Infant Survival Rate,Free Tuberculosis cases rate,Private spending on health (% of GDP),Public spending on health (% of GDP),Total spending on health (% of GDP),"Public Spending on health per capita, PPP $","Private Spending on health per capita, PPP $","Total Spending on health per capita, PPP $","Health expenditure, private (% of GDP) [SH.XPD.PRIV.ZS]","Health expenditure, public (% of GDP) [SH.XPD.PUBL.ZS]","Health expenditure per capita, PPP (constant 2011 international $) [SH.XPD.PCAP.PP.KD]","Health expenditure, public (% of government expenditure) [SH.XPD.PUBL.GX.ZS]"
0,country,year,igroup,lifebirth,imdpt,immea,dale,matmortalityrat,infantmortalitrat,tbpc,hprivgdp,hpubgdp,htotGDP,heappp,privheappp,htotppp,healthexp_private,helathexp_pub,pchealthexp_11cons,healthpubshare
1,Angola,2006,Lower middle income,53.9271,34,33,56.89,NaN,0.9037,NaN,0.0152,0.030224,0.045424,139.0657,69.93706,209.0028,1.520002,3.022435,209.61484,9.564669
2,Angola,2007,Lower middle income,55.0475,73,71,NaN,NaN,0.9091,NaN,0.011694,0.022138,0.033831,120.498,63.64907,184.147,1.169348,2.213764,189.90187,6.416707
3,Angola,2008,Lower middle income,56.1393,69,61,NaN,NaN,0.9144,NaN,0.011286,0.027163,0.038449,162.3916,67.47146,229.863,1.128599,2.716334,242.15426,6.464507
4,Angola,2009,Lower middle income,57.181,60,57,NaN,NaN,0.9197,NaN,0.017079,0.026639,0.043718,157.3856,100.9011,258.2867,1.707857,2.663917,274.73451,6.358449
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1932,Zimbabwe,2012,Low income,56.4077,95,97,NaN,NaN,0.9492,0.99367,0.039146,0.027716,0.066862,51.2249,72.3487,123.5736,3.914563,2.77162,112.2178,9.691281
1933,Zimbabwe,2013,Low income,57.9405,95,93,NaN,NaN,0.9522,0.99397,0.040314,0.028474,0.068788,54.13524,76.64409,130.7793,4.031388,2.84745,119.73334,9.593592
1934,Zimbabwe,2014,Low income,59.2443,91,92,NaN,NaN,0.9556,0.99438,0.03973,0.024665,0.064395,47.07251,75.82336,122.8959,3.972976,2.466495,114.60851,8.486653
1935,Zimbabwe,2015,Low income,60.2793,87,86,NaN,0.99557,0.958,0.99448,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1936,Zimbabwe,2016,Low income,NaN,90,95,59.2,NaN,0.96,0.99722,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
efficiency.columns

Index(['Country name', 'Year', 'Income group classification',
       'Life expectancy at birth', 'Immunization DPT', 'Immunization Measles',
       'Disability Adjusted Life Exectancy', 'Maternal Survival Rate',
       'Infant Survival Rate', 'Free Tuberculosis cases rate',
       'Private spending on health (% of GDP)',
       'Public spending on health (% of GDP)',
       'Total spending on health (% of GDP)',
       'Public Spending on health per capita, PPP $',
       'Private Spending on health per capita, PPP $',
       'Total Spending on health per capita, PPP $',
       'Health expenditure, private (% of GDP) [SH.XPD.PRIV.ZS]',
       'Health expenditure, public (% of GDP) [SH.XPD.PUBL.ZS]',
       'Health expenditure per capita, PPP (constant 2011 international $) [SH.XPD.PCAP.PP.KD]',
       'Health expenditure, public (% of government expenditure) [SH.XPD.PUBL.GX.ZS]'],
      dtype='object')

In [21]:
efficiency.columns = ['Country',
                   'Year','Income group classification',
                   'Life expectancy at birth',
                   'Immunization DPT',
                   'Immunization Measles',
                   'Disability Adjusted Life Exectancy',
                   'Maternal Survival Rate',
                   'Infant Survival Rate',
                   'Free Tuberculosis cases rate',
                   'Private spending on health (% of GDP)',
                   'Public spending on health (% of GDP)',
                   'Total spending on health (% of GDP)',
                   'Public Spending on health per capita, PPP $',
                   'Private Spending on health per capita, PPP $',
                   'Total Spending on health per capita, PPP $',
                   'Health expenditure, private (% of GDP)',
                   'Health expenditure, public (% of GDP)',
                   'Health expenditure per capita, PPP (constant 2011 international $)',
                   'Health expenditure, public (% of government expenditure)']

In [22]:
efficiency

,Country,Year,Income group classification,Life expectancy at birth,Immunization DPT,Immunization Measles,Disability Adjusted Life Exectancy,Maternal Survival Rate,Infant Survival Rate,Free Tuberculosis cases rate,Private spending on health (% of GDP),Public spending on health (% of GDP),Total spending on health (% of GDP),"Public Spending on health per capita, PPP $","Private Spending on health per capita, PPP $","Total Spending on health per capita, PPP $","Health expenditure, private (% of GDP)","Health expenditure, public (% of GDP)","Health expenditure per capita, PPP (constant 2011 international $)","Health expenditure, public (% of government expenditure)"
0,country,year,igroup,lifebirth,imdpt,immea,dale,matmortalityrat,infantmortalitrat,tbpc,hprivgdp,hpubgdp,htotGDP,heappp,privheappp,htotppp,healthexp_private,helathexp_pub,pchealthexp_11cons,healthpubshare
1,Angola,2006,Lower middle income,53.9271,34,33,56.89,NaN,0.9037,NaN,0.0152,0.030224,0.045424,139.0657,69.93706,209.0028,1.520002,3.022435,209.61484,9.564669
2,Angola,2007,Lower middle income,55.0475,73,71,NaN,NaN,0.9091,NaN,0.011694,0.022138,0.033831,120.498,63.64907,184.147,1.169348,2.213764,189.90187,6.416707
3,Angola,2008,Lower middle income,56.1393,69,61,NaN,NaN,0.9144,NaN,0.011286,0.027163,0.038449,162.3916,67.47146,229.863,1.128599,2.716334,242.15426,6.464507
4,Angola,2009,Lower middle income,57.181,60,57,NaN,NaN,0.9197,NaN,0.017079,0.026639,0.043718,157.3856,100.9011,258.2867,1.707857,2.663917,274.73451,6.358449
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1932,Zimbabwe,2012,Low income,56.4077,95,97,NaN,NaN,0.9492,0.99367,0.039146,0.027716,0.066862,51.2249,72.3487,123.5736,3.914563,2.77162,112.2178,9.691281
1933,Zimbabwe,2013,Low income,57.9405,95,93,NaN,NaN,0.9522,0.99397,0.040314,0.028474,0.068788,54.13524,76.64409,130.7793,4.031388,2.84745,119.73334,9.593592
1934,Zimbabwe,2014,Low income,59.2443,91,92,NaN,NaN,0.9556,0.99438,0.03973,0.024665,0.064395,47.07251,75.82336,122.8959,3.972976,2.466495,114.60851,8.486653
1935,Zimbabwe,2015,Low income,60.2793,87,86,NaN,0.99557,0.958,0.99448,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1936,Zimbabwe,2016,Low income,NaN,90,95,59.2,NaN,0.96,0.99722,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
efficiency = efficiency.drop([0])

In [26]:
#use the melt and verticalize data 

efficiency_df = pd.melt(efficiency, id_vars=['Country','Year','Income group classification'])
efficiency_df = efficiency_df.rename(columns={'variable':'parameter', 'value':'value'})
efficiency_df

,Country,Year,Income group classification,parameter,value
0,Angola,2006,Lower middle income,Life expectancy at birth,53.9271
1,Angola,2007,Lower middle income,Life expectancy at birth,55.0475
2,Angola,2008,Lower middle income,Life expectancy at birth,56.1393
3,Angola,2009,Lower middle income,Life expectancy at birth,57.181
4,Angola,2010,Lower middle income,Life expectancy at birth,58.1411
...,...,...,...,...,...
32907,Zimbabwe,2012,Low income,"Health expenditure, public (% of government ex...",9.691281
32908,Zimbabwe,2013,Low income,"Health expenditure, public (% of government ex...",9.593592
32909,Zimbabwe,2014,Low income,"Health expenditure, public (% of government ex...",8.486653
32910,Zimbabwe,2015,Low income,"Health expenditure, public (% of government ex...",NaN
32911,Zimbabwe,2016,Low income,"Health expenditure, public (% of government ex...",NaN

In [27]:
#########################

In [28]:
# Health Equity And Financial Protection Indicators

## Dataset location: https://datacatalog.worldbank.org/dataset/hefpi

file_name = "https://databank.worldbank.org/data/download/HEFPI_Excel.ZIP"

## First lets see all documents in zipfile

RemoteZip(file_name).namelist()

## Lets choose which data we need

file = RemoteZip(file_name).open('HEFPIEXCEL.xlsx').read()

## Read and made a dataframe

equity_complete = pd.read_excel(file, sheet_name='Data')
equity_complete.head(50)

,Country Name,Country Code,Indicator Name,Indicator Code,1982,1983,1984,1985,1986,1987,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,Afghanistan,AFG,Acute respiratory infections treated (% of chi...,HF.STA.ARIC.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,60.355908,NaN,NaN,NaN,NaN,61.427754,NaN,NaN,NaN
1,Afghanistan,AFG,Acute respiratory infections treated (% of chi...,HF.STA.ARIC.ZS.Q1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,45.818409,NaN,NaN,NaN,NaN,54.306960,NaN,NaN,NaN
2,Afghanistan,AFG,Acute respiratory infections treated (% of chi...,HF.STA.ARIC.ZS.Q2,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,59.437793,NaN,NaN,NaN,NaN,65.181047,NaN,NaN,NaN
3,Afghanistan,AFG,Acute respiratory infections treated (% of chi...,HF.STA.ARIC.ZS.Q3,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,65.523684,NaN,NaN,NaN,NaN,57.236749,NaN,NaN,NaN
4,Afghanistan,AFG,Acute respiratory infections treated (% of chi...,HF.STA.ARIC.ZS.Q4,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,63.517118,NaN,NaN,NaN,NaN,66.636157,NaN,NaN,NaN
5,Afghanistan,AFG,Acute respiratory infections treated (% of chi...,HF.STA.ARIC.ZS.Q5,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,65.635198,NaN,NaN,NaN,NaN,66.827649,NaN,NaN,NaN
6,Afghanistan,AFG,Births attended by skilled health staff (% of ...,HF.STA.BRTC.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,39.496449,NaN,NaN,NaN,NaN,56.935620,NaN,NaN,NaN
7,Afghanistan,AFG,Births attended by skilled health staff (% of ...,HF.STA.BRTC.ZS.Q1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,16.027388,NaN,NaN,NaN,NaN,28.941539,NaN,NaN,NaN
8,Afghanistan,AFG,Births attended by skilled health staff (% of ...,HF.STA.BRTC.ZS.Q2,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,25.704494,NaN,NaN,NaN,NaN,41.874418,NaN,NaN,NaN
9,Afghanistan,AFG,Births attended by skilled health staff (% of ...,HF.STA.BRTC.ZS.Q3,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,31.810951,NaN,NaN,NaN,NaN,51.442975,NaN,NaN,NaN
10,Afghanistan,AFG,Births attended by skilled health staff (% of ...,HF.STA.BRTC.ZS.Q4,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,47.292688,NaN,NaN,NaN,NaN,70.557326,NaN,NaN,NaN
11,Afghanistan,AFG,Births attended by skilled health staff (% of ...,HF.STA.BRTC.ZS.Q5,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,76.822156,NaN,NaN,NaN,NaN,88.216317,NaN,NaN,NaN
12,Afghanistan,AFG,Blood pressure measured in last 12 months (% o...,HF.STA.BP18.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Afghanistan,AFG,Blood pressure measured in last 12 months (% o...,HF.STA.BP18.ZS.Q1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Afghanistan,AFG,Blood pressure measured in last 12 months (% o...,HF.STA.BP18.ZS.Q2,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Afghanistan,AFG,Blood pressure measured in last 12 months (% o...,HF.STA.BP18.ZS.Q3,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Afghanistan,AFG,Blood pressure measured in last 12 months (% o...,HF.STA.BP18.ZS.Q4,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Afghanistan,AFG,Blood pressure measured in last 12 months (% o...,HF.STA.BP18.ZS.Q5,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Afghanistan,AFG,Blood sugar measured in last 5 years (% of pop...,HF.STA.BLSG.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Afghanistan,AFG,Blood sugar measured in last 5 years (% of pop...,HF.STA.BLSG.ZS.Q1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Afghanistan,AFG,Blood sugar measured in last 5 years (% of pop...,HF.STA.BLSG.ZS.Q2,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Afghanistan,AFG,Blood sugar measured in last 5 years (% of pop...,HF.STA.BLSG.ZS.Q3,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Afghanistan,AFG,Blood sugar measured in last 5 years (% of pop...,HF.STA.BLSG.ZS.Q4,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,Afghanistan,AFG,Blood sugar measured in last 5 years (% of pop...,HF.STA.BLSG.ZS.Q5,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,Afghanistan,AFG,Change in poverty gap due to out-of-pocket hea...,HF.UHC.NOP1.CG,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.036824,NaN,NaN,NaN,NaN,NaN
25,Afghanistan,AFG,Change in poverty gap due to out-of-pocket hea...,HF.UHC.NOP4.CG,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.141547,NaN,NaN,NaN,NaN,NaN
26,Afghanistan,AFG,Change in poverty gap due to out-of-pocket hea...,HF.UHC.NOP2.CG,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.091303,NaN,NaN,NaN,NaN,NaN
27,Afghanistan,AFG,Change in poverty gap due to out-of-pocket hea...,HF.UHC.NOP3.CG,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.127618,NaN,NaN,NaN,NaN,NaN
28,Afghanistan,AFG,Cholesterol measured in last five years (% of ...,HF.STA.CHOM.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Afghanistan,AFG,Cholesterol measured in last five years (% of ...,HF.STA.CHOM.ZS.Q1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,Afghanistan,AFG,Cholesterol measured in last five years (% of ...,HF.STA.CHOM.ZS.Q2,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,Afghanistan,AFG,Cholesterol measured in last five years (% of ...,HF.STA.CHOM.ZS.Q3,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,Afghanistan,AFG,Cholesterol measured in last five years (% of ...,HF.STA.CHOM.ZS.Q4,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,Afghanistan,AFG,Cholesterol measured in last five years (% of ...,HF.STA.CHOM.ZS.Q5,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,Afghanistan,AFG,Condom use in last intercourse (% of females a...,HF.CON.AIDS.FE.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,Afghanistan,AFG,Condom use in last intercourse (% of females a...,HF.CON.AIDS.FE.ZS.Q1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,Afghanistan,AFG,Condom use in last intercourse (% of females a...,HF.CON.AIDS.FE.ZS.Q2,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,Afghanistan,AFG,Condom use in last intercourse (% of females a...,HF.CON.AIDS.FE.ZS.Q3,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,Afghanistan,AFG,Condom use in last intercourse (% of females a...,HF.CON.AIDS.FE.ZS.Q4,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,Afghanistan,AFG,Condom use in last intercourse (% of females a...,HF.CON.AIDS.FE.ZS.Q5,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,Afghanistan,AFG,"Contraceptive prevalence, modern methods (% of...",HF.DYN.CONM.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,26.375878,NaN,NaN,NaN,NaN,19.784079,NaN,NaN,NaN
41,Afghanistan,AFG,"Contraceptive prevalence, modern methods (% of...",HF.DYN.CONM.ZS.Q1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,19.383904,NaN,NaN,NaN,NaN,15.078956,NaN,NaN,NaN
42,Afghanistan,AFG,"Contraceptive prevalence, modern methods (% of...",HF.DYN.CONM.ZS.Q2,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,17.006230,NaN,NaN,NaN,NaN,16.088511,NaN,NaN,NaN
43,Afghanistan,AFG,"Contraceptive prevalence, modern methods (% of...",HF.DYN.CONM.ZS.Q3,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,24.629942,NaN,NaN,NaN,NaN,15.702316,NaN,NaN,NaN
44,Afghanistan,AFG,"Contraceptive prevalence, modern methods (% of...",HF.DYN.CONM.ZS.Q4,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,28.917149,NaN,NaN,NaN,NaN,21.986535,NaN,NaN,NaN
45,Afghanistan,AFG,"Contraceptive prevalence, modern methods (% of...",HF.DYN.CONM.ZS.Q5,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,41.859415,NaN,NaN,NaN,NaN,30.510512,NaN,NaN,NaN
46,Afghanistan,AFG,Diarrhea treatment (% of children under 5 who ...,HF.STA.ORTH.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,53.636473,NaN,NaN,NaN,NaN,46.944037,NaN,NaN,NaN
47,Afghanistan,AFG,Diarrhea treatment (% of children under 5 who ...,HF.STA.ORTH.ZS.Q1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,56.235081,NaN,NaN,NaN,NaN,45.832473,NaN,NaN,NaN
48,Afghanistan,AFG,Diarrhea treatment (% of children under 5 who ...,HF.STA.ORTH.ZS.Q2,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,51.092482,NaN,NaN,NaN,NaN,48.921460,NaN,NaN,NaN
49,Afghanistan,AFG,Diarrhea treatment (% of children under 5 who ...,HF.STA.ORTH.ZS.Q3,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,52.923226,NaN,NaN,NaN,NaN,45.903113,NaN,NaN,NaN

In [29]:
## Lets clean the dataframe

## see column names

equity_complete['Indicator Name'].unique()

array(['Acute respiratory infections treated (% of children under 5 with cough and rapid breathing)',
       'Acute respiratory infections treated (% of children under 5 with cough and rapid breathing): Q1 (lowest)',
       'Acute respiratory infections treated (% of children under 5 with cough and rapid breathing): Q2',
       'Acute respiratory infections treated (% of children under 5 with cough and rapid breathing): Q3',
       'Acute respiratory infections treated (% of children under 5 with cough and rapid breathing): Q4',
       'Acute respiratory infections treated (% of children under 5 with cough and rapid breathing): Q5 (highest)',
       'Births attended by skilled health staff (% of total)',
       'Births attended by skilled health staff (% of total): Q1 (lowest)',
       'Births attended by skilled health staff (% of total): Q2',
       'Births attended by skilled health staff (% of total): Q3',
       'Births attended by skilled health staff (% of total): Q4',
       'Births attended by skilled health staff (% of total): Q5 (highest)',
       'Blood pressure measured in last 12 months (% of population age 18+)',
       'Blood pressure measured in last 12 months (% of population age 18+): Q1 (lowest)',
       'Blood pressure measured in last 12 months (% of population age 18+): Q2',
       'Blood pressure measured in last 12 months (% of population age 18+): Q3',
       'Blood pressure measured in last 12 months (% of population age 18+): Q4',
       'Blood pressure measured in last 12 months (% of population age 18+): Q5 (highest)',
       'Blood sugar measured in last 5 years (% of population at risk of diabetes)',
       'Blood sugar measured in last 5 years (% of population at risk of diabetes): Q1 (lowest)',
       'Blood sugar measured in last 5 years (% of population at risk of diabetes): Q2',
       'Blood sugar measured in last 5 years (% of population at risk of diabetes): Q3',
       'Blood sugar measured in last 5 years (% of population at risk of diabetes): Q4',
       'Blood sugar measured in last 5 years (% of population at risk of diabetes): Q5 (highest)',
       'Change in poverty gap due to out-of-pocket health spending ($ 2011 PPP), $1.90 poverty line',
       'Change in poverty gap due to out-of-pocket health spending ($ 2011 PPP), $21.70 poverty line',
       'Change in poverty gap due to out-of-pocket health spending ($ 2011 PPP), $3.20 poverty line',
       'Change in poverty gap due to out-of-pocket health spending ($ 2011 PPP), $5.50 poverty line',
       'Cholesterol measured in last five years (% of population at risk of high cholesterol)',
       'Cholesterol measured in last five years (% of population at risk of high cholesterol): Q1 (lowest)',
       'Cholesterol measured in last five years (% of population at risk of high cholesterol): Q2',
       'Cholesterol measured in last five years (% of population at risk of high cholesterol): Q3',
       'Cholesterol measured in last five years (% of population at risk of high cholesterol): Q4',
       'Cholesterol measured in last five years (% of population at risk of high cholesterol): Q5 (highest)',
       'Condom use in last intercourse (% of females at risk population)',
       'Condom use in last intercourse (% of females at risk population): Q1 (lowest)',
       'Condom use in last intercourse (% of females at risk population): Q2',
       'Condom use in last intercourse (% of females at risk population): Q3',
       'Condom use in last intercourse (% of females at risk population): Q4',
       'Condom use in last intercourse (% of females at risk population): Q5 (highest)',
       'Contraceptive prevalence, modern methods (% of females ages 15-49)',
       'Contraceptive prevalence, modern methods (% of females ages 15-49): Q1 (lowest)',
       'Contraceptive prevalence, modern methods (% of females ages 15-49): Q2',
       'Contraceptive prevalence, modern methods (% of females ages 15-49): Q3',
       'Contraceptive prevalence, modern methods (% of females ages 15-49): Q4',
       'Contraceptive prevalence, modern methods (% of females ages 15-49): Q5 (highest)',
       'Diarrhea treatment (% of children under 5 who received ORS)',
       'Diarrhea treatment (% of children under 5 who received ORS): Q1 (lowest)',
       'Diarrhea treatment (% of children under 5 who received ORS): Q2',
       'Diarrhea treatment (% of children under 5 who received ORS): Q3',
       'Diarrhea treatment (% of children under 5 who received ORS): Q4',
       'Diarrhea treatment (% of children under 5 who received ORS): Q5 (highest)',
       'High blood pressure or being treated for high blood pressure (% of adult population)',
       'High blood pressure or being treated for high blood pressure (% of adult population): Q1 (lowest)',
       'High blood pressure or being treated for high blood pressure (% of adult population): Q2',
       'High blood pressure or being treated for high blood pressure (% of adult population): Q3',
       'High blood pressure or being treated for high blood pressure (% of adult population): Q4',
       'High blood pressure or being treated for high blood pressure (% of adult population): Q5 (highest)',
       'High cholesterol or on treatment for high cholesterol (% of adult population)',
       'Immunization, full (% of children ages 15-23 months)',
       'Immunization, full (% of children ages 15-23 months): Q1 (lowest)',
       'Immunization, full (% of children ages 15-23 months): Q2',
       'Immunization, full (% of children ages 15-23 months): Q3',
       'Immunization, full (% of children ages 15-23 months): Q4',
       'Immunization, full (% of children ages 15-23 months): Q5 (highest)',
       'Immunization, measles (% of children ages 15-23 months)',
       'Immunization, measles (% of children ages 15-23 months): Q1 (lowest)',
       'Immunization, measles (% of children ages 15-23 months): Q2',
       'Immunization, measles (% of children ages 15-23 months): Q3',
       'Immunization, measles (% of children ages 15-23 months): Q4',
       'Immunization, measles (% of children ages 15-23 months): Q5 (highest)',
       'Impaired fasting glycaemia (% of adult population)',
       'Inpatient care use in last 12 months (% of population 18+)',
       'Inpatient care use in last 12 months (% of population 18+): Q1 (lowest)',
       'Inpatient care use in last 12 months (% of population 18+): Q2',
       'Inpatient care use in last 12 months (% of population 18+): Q3',
       'Inpatient care use in last 12 months (% of population 18+): Q4',
       'Inpatient care use in last 12 months (% of population 18+): Q5 (highest)',
       'Mammography in last 2 years, (% of females 50-69)',
       'Mammography in last 2 years, (% of females 50-69): Q1 (lowest)',
       'Mammography in last 2 years, (% of females 50-69): Q2',
       'Mammography in last 2 years, (% of females 50-69): Q3',
       'Mammography in last 2 years, (% of females 50-69): Q4',
       'Mammography in last 2 years, (% of females 50-69): Q5 (highest)',
       'Mean BMI, adults (age 18+)',
       'Mean BMI, adults (age 18+): Q1 (lowest)',
       'Mean BMI, adults (age 18+): Q2', 'Mean BMI, adults (age 18+): Q3',
       'Mean BMI, adults (age 18+): Q4',
       'Mean BMI, adults (age 18+): Q5 (highest)',
       'Mean BMI, female (age 18+)',
       'Mean BMI, female (age 18+): Q1 (lowest)',
       'Mean BMI, female (age 18+): Q2', 'Mean BMI, female (age 18+): Q3',
       'Mean BMI, female (age 18+): Q4',
       'Mean BMI, female (age 18+): Q5 (highest)',
       'Mean BMI, female (ages 15-49)',
       'Mean BMI, female (ages 15-49): Q1 (lowest)',
       'Mean BMI, female (ages 15-49): Q2',
       'Mean BMI, female (ages 15-49): Q3',
       'Mean BMI, female (ages 15-49): Q4',
       'Mean BMI, female (ages 15-49): Q5 (highest)',
       'Mean BMI, male (age 18+)',
       'Mean BMI, male (age 18+): Q1 (lowest)',
       'Mean BMI, male (age 18+): Q2', 'Mean BMI, male (age 18+): Q3',
       'Mean BMI, male (age 18+): Q4',
       'Mean BMI, male (age 18+): Q5 (highest)',
       'Mean cholesterol, adult population (mmol/L)',
       'Mean diastolic blood pressure, adult population (mmHg)',
       'Mean diastolic blood pressure, adult population (mmHg): Q1 (lowest)',
       'Mean diastolic blood pressure, adult population (mmHg): Q2',
       'Mean diastolic blood pressure, adult population (mmHg): Q3',
       'Mean diastolic blood pressure, adult population (mmHg): Q4',
       'Mean diastolic blood pressure, adult population (mmHg): Q5 (highest)',
       'Mean fasting blood glucose, adult population (mmol/L)',
       'Mean height in meters, adults (age 18+)',
       'Mean height in meters, adults (age 18+): Q1 (lowest)',
       'Mean height in meters, adults (age 18+): Q2',
       'Mean height in meters, adults (age 18+): Q3',
       'Mean height in meters, adults (age 18+): Q4',
       'Mean height in meters, adults (age 18+): Q5 (highest)',
       'Mean height in meters, female (age 18+)',
       'Mean height in meters, female (age 18+): Q1 (lowest)',
       'Mean height in meters, female (age 18+): Q2',
       'Mean height in meters, female (age 18+): Q3',
       'Mean height in meters, female (age 18+): Q4',
       'Mean height in meters, female (age 18+): Q5 (highest)',
       'Mean height in meters, female, (age 15-49)',
       'Mean height in meters, female, (age 15-49): Q1 (lowest)',
       'Mean height in meters, female, (age 15-49): Q2',
       'Mean height in meters, female, (age 15-49): Q3',
       'Mean height in meters, female, (age 15-49): Q4',
       'Mean height in meters, female, (age 15-49): Q5 (highest)',
       'Mean height in meters, male (age 18+)',
       'Mean height in meters, male (age 18+): Q1 (lowest)',
       'Mean height in meters, male (age 18+): Q2',
       'Mean height in meters, male (age 18+): Q3',
       'Mean height in meters, male (age 18+): Q4',
       'Mean height in meters, male (age 18+): Q5 (highest)',
       'Mean household per capita out-of-pocket health spending ($ 2011 PPP)',
       'Mean share of household consumption or income used on out-of-pocket health spending (%)',
       'Mean share of household consumption or income used on out-of-pocket health spending (%): Q1 (lowest)',
       'Mean share of household consumption or income used on out-of-pocket health spending (%): Q2',
       'Mean share of household consumption or income used on out-of-pocket health spending (%): Q3',
       'Mean share of household consumption or income used on out-of-pocket health spending (%): Q4',
       'Mean share of household consumption or income used on out-of-pocket health spending (%): Q5 (highest)',
       'Mean systolic blood pressure, adult population (mmHg)',
       'Mean systolic blood pressure, adult population (mmHg): Q1 (lowest)',
       'Mean systolic blood pressure, adult population (mmHg): Q2',
       'Mean systolic blood pressure, adult population (mmHg): Q3',
       'Mean systolic blood pressure, adult population (mmHg): Q4',
       'Mean systolic blood pressure, adult population (mmHg): Q5 (highest)',
       'Mortality rate, infant (per 1,000 live births)',
       'Mortality rate, infant (per 1,000 live births): Q1 (lowest)',
       'Mortality rate, infant (per 1,000 live births): Q2',
       'Mortality rate, infant (per 1,000 live births): Q3',
       'Mortality rate, infant (per 1,000 live births): Q4',
       'Mortality rate, infant (per 1,000 live births): Q5 (highest)',
       'Mortality rate, under-5 (per 1,000)',
       'Mortality rate, under-5 (per 1,000): Q1 (lowest)',
       'Mortality rate, under-5 (per 1,000): Q2',
       'Mortality rate, under-5 (per 1,000): Q3',
       'Mortality rate, under-5 (per 1,000): Q4',
       'Mortality rate, under-5 (per 1,000): Q5 (highest)',
       'Pap smear in last 5 years (% of females 30-49)',
       'Pap smear in last 5 years (% of females 30-49): Q1 (lowest)',
       'Pap smear in last 5 years (% of females 30-49): Q2',
       'Pap smear in last 5 years (% of females 30-49): Q3',
       'Pap smear in last 5 years (% of females 30-49): Q4',
       'Pap smear in last 5 years (% of females 30-49): Q5 (highest)',
       'Pregnant women receiving prenatal care of at least four visits (% of pregnant women)',
       'Pregnant women receiving prenatal care of at least four visits (% of pregnant women): Q1 (lowest)',
       'Pregnant women receiving prenatal care of at least four visits (% of pregnant women): Q2',
       'Pregnant women receiving prenatal care of at least four visits (% of pregnant women): Q3',
       'Pregnant women receiving prenatal care of at least four visits (% of pregnant women): Q4',
       'Pregnant women receiving prenatal care of at least four visits (% of pregnant women): Q5 (highest)',
       'Prevalence of HIV, total (% of population ages 15-49)',
       'Prevalence of HIV, total (% of population ages 15-49): Q1 (lowest)',
       'Prevalence of HIV, total (% of population ages 15-49): Q2',
       'Prevalence of HIV, total (% of population ages 15-49): Q3',
       'Prevalence of HIV, total (% of population ages 15-49): Q4',
       'Prevalence of HIV, total (% of population ages 15-49): Q5 (highest)',
       'Prevalence of obesity, BMI > 30 (% of population 18+)',
       'Prevalence of obesity, BMI > 30 (% of population 18+): Q1 (lowest)',
       'Prevalence of obesity, BMI > 30 (% of population 18+): Q2',
       'Prevalence of obesity, BMI > 30 (% of population 18+): Q3',
       'Prevalence of obesity, BMI > 30 (% of population 18+): Q4',
       'Prevalence of obesity, BMI > 30 (% of population 18+): Q5 (highest)',
       'Prevalence of obesity, female, BMI > 30 (% of population 15-49)',
       'Prevalence of obesity, female, BMI > 30 (% of population 15-49): Q1 (lowest)',
       'Prevalence of obesity, female, BMI > 30 (% of population 15-49): Q2',
       'Prevalence of obesity, female, BMI > 30 (% of population 15-49): Q3',
       'Prevalence of obesity, female, BMI > 30 (% of population 15-49): Q4',
       'Prevalence of obesity, female, BMI > 30 (% of population 15-49): Q5 (highest)',
       'Prevalence of obesity, female, BMI > 30 (% of population 18+)',
       'Prevalence of obesity, female, BMI > 30 (% of population 18+): Q1 (lowest)',
       'Prevalence of obesity, female, BMI > 30 (% of population 18+): Q2',
       'Prevalence of obesity, female, BMI > 30 (% of population 18+): Q3',
       'Prevalence of obesity, female, BMI > 30 (% of population 18+): Q4',
       'Prevalence of obesity, female, BMI > 30 (% of population 18+): Q5 (highest)',
       'Prevalence of obesity, male, BMI > 30 (% of population 18+)',
       'Prevalence of obesity, male, BMI > 30 (% of population 18+): Q1 (lowest)',
       'Prevalence of obesity, male, BMI > 30 (% of population 18+): Q2',
       'Prevalence of obesity, male, BMI > 30 (% of population 18+): Q3',
       'Prevalence of obesity, male, BMI > 30 (% of population 18+): Q4',
       'Prevalence of obesity, male, BMI > 30 (% of population 18+): Q5 (highest)',
       'Prevalence of overweight, BMI > 25 (% of population 18+)',
       'Prevalence of overweight, BMI > 25 (% of population 18+): Q1 (lowest)',
       'Prevalence of overweight, BMI > 25 (% of population 18+): Q2',
       'Prevalence of overweight, BMI > 25 (% of population 18+): Q3',
       'Prevalence of overweight, BMI > 25 (% of population 18+): Q4',
       'Prevalence of overweight, BMI > 25 (% of population 18+): Q5 (highest)',
       'Prevalence of overweight, female, BMI > 25 (% of population 18+)',
       'Prevalence of overweight, female, BMI > 25 (% of population 18+): Q1 (lowest)',
       'Prevalence of overweight, female, BMI > 25 (% of population 18+): Q2',
       'Prevalence of overweight, female, BMI > 25 (% of population 18+): Q3',
       'Prevalence of overweight, female, BMI > 25 (% of population 18+): Q4',
       'Prevalence of overweight, female, BMI > 25 (% of population 18+): Q5 (highest)',
       'Prevalence of overweight, female, BMI > 25 (% of population ages 15-49)',
       'Prevalence of overweight, female, BMI > 25 (% of population ages 15-49): Q1 (lowest)',
       'Prevalence of overweight, female, BMI > 25 (% of population ages 15-49): Q2',
       'Prevalence of overweight, female, BMI > 25 (% of population ages 15-49): Q3',
       'Prevalence of overweight, female, BMI > 25 (% of population ages 15-49): Q4',
       'Prevalence of overweight, female, BMI > 25 (% of population ages 15-49): Q5 (highest)',
       'Prevalence of overweight, male, BMI > 25 (% of population 18+)',
       'Prevalence of overweight, male, BMI > 25 (% of population 18+): Q1 (lowest)',
       'Prevalence of overweight, male, BMI > 25 (% of population 18+): Q2',
       'Prevalence of overweight, male, BMI > 25 (% of population 18+): Q3',
       'Prevalence of overweight, male, BMI > 25 (% of population 18+): Q4',
       'Prevalence of overweight, male, BMI > 25 (% of population 18+): Q5 (highest)',
       'Prevalence of stunting, height for age (% of children under 5)',
       'Prevalence of stunting, height for age (% of children under 5): Q1 (lowest)',
       'Prevalence of stunting, height for age (% of children under 5): Q2',
       'Prevalence of stunting, height for age (% of children under 5): Q3',
       'Prevalence of stunting, height for age (% of children under 5): Q4',
       'Prevalence of stunting, height for age (% of children under 5): Q5 (highest)',
       'Prevalence of underweight, weight for age (% of children under 5)',
       'Prevalence of underweight, weight for age (% of children under 5): Q1 (lowest)',
       'Prevalence of underweight, weight for age (% of children under 5): Q2',
       'Prevalence of underweight, weight for age (% of children under 5): Q3',
       'Prevalence of underweight, weight for age (% of children under 5): Q4',
       'Prevalence of underweight, weight for age (% of children under 5): Q5 (highest)',
       'Proportion of population pushed below the $1.90 ($ 2011 PPP) poverty line by out-of-pocket health care expenditure (%)',
       'Proportion of population pushed below the $1.90 ($ 2011 PPP) poverty line by out-of-pocket health care expenditure (%): Q1 (lowest)',
       'Proportion of population pushed below the $1.90 ($ 2011 PPP) poverty line by out-of-pocket health care expenditure (%): Q2',
       'Proportion of population pushed below the $1.90 ($ 2011 PPP) poverty line by out-of-pocket health care expenditure (%): Q3',
       'Proportion of population pushed below the $1.90 ($ 2011 PPP) poverty line by out-of-pocket health care expenditure (%): Q4',
       'Proportion of population pushed below the $1.90 ($ 2011 PPP) poverty line by out-of-pocket health care expenditure (%): Q5 (highest)',
       'Proportion of population pushed below the $21.70 ($ 2011 PPP) poverty line by out-of-pocket health care expenditure (%)',
       'Proportion of population pushed below the $21.70 ($ 2011 PPP) poverty line by out-of-pocket health care expenditure (%): Q1 (lowest)',
       'Proportion of population pushed below the $21.70 ($ 2011 PPP) poverty line by out-of-pocket health care expenditure (%): Q2',
       'Proportion of population pushed below the $21.70 ($ 2011 PPP) poverty line by out-of-pocket health care expenditure (%): Q3',
       'Proportion of population pushed below the $21.70 ($ 2011 PPP) poverty line by out-of-pocket health care expenditure (%): Q4',
       'Proportion of population pushed below the $21.70 ($ 2011 PPP) poverty line by out-of-pocket health care expenditure (%): Q5 (highest)',
       'Proportion of population pushed below the $3.20 ($ 2011 PPP) poverty line by out-of-pocket health care expenditure (%)',
       'Proportion of population pushed below the $3.20 ($ 2011 PPP) poverty line by out-of-pocket health care expenditure (%): Q1 (lowest)',

In [30]:
equity = equity_complete[
    (equity_complete['Indicator Name'] =='Acute respiratory infections treated (% of children under 5 with cough and rapid breathing)') |
    (equity_complete['Indicator Name'] =='Births attended by skilled health staff (% of total)') |
    (equity_complete['Indicator Name'] =='Blood pressure measured in last 12 months (% of population age 18+)') |
    (equity_complete['Indicator Name'] =='Blood sugar measured in last 5 years (% of population at risk of diabetes)') |
    (equity_complete['Indicator Name'] =='Cholesterol measured in last five years (% of population at risk of high cholesterol)') |
    (equity_complete['Indicator Name'] =='Condom use in last intercourse (% of females at risk population)') |
    (equity_complete['Indicator Name'] =='Contraceptive prevalence, modern methods (% of females ages 15-49)')|
    (equity_complete['Indicator Name'] =='Diarrhea treatment (% of children under 5 who received ORS)') |
    (equity_complete['Indicator Name'] =='High blood pressure or being treated for high blood pressure (% of adult population)') |
    (equity_complete['Indicator Name'] =='High cholesterol or on treatment for high cholesterol (% of adult population)') |
    (equity_complete['Indicator Name'] =='Immunization, full (% of children ages 15-23 months)') |
    (equity_complete['Indicator Name'] =='Immunization, measles (% of children ages 15-23 months)') | 
    (equity_complete['Indicator Name'] =='Impaired fasting glycaemia (% of adult population)') |
    (equity_complete['Indicator Name'] =='Inpatient care use in last 12 months (% of population 18+)') |
    (equity_complete['Indicator Name'] =='Mammography in last 2 years, (% of females 50-69)') |
    (equity_complete['Indicator Name'] =='Mean BMI, adults (age 18+)') |
    (equity_complete['Indicator Name'] =='Mean BMI, female (age 18+)') |
    (equity_complete['Indicator Name'] =='Mean BMI, female (ages 15-49)') | 
    (equity_complete['Indicator Name'] =='Mean BMI, male (age 18+)') |
    (equity_complete['Indicator Name'] =='Mean cholesterol, adult population (mmol/L)') |
    (equity_complete['Indicator Name'] =='Mean diastolic blood pressure, adult population (mmHg)') |
    (equity_complete['Indicator Name'] =='Mean fasting blood glucose, adult population (mmol/L)') |
    (equity_complete['Indicator Name'] =='Mean height in meters, adults (age 18+)') |
    (equity_complete['Indicator Name'] =='Mean height in meters, female (age 18+)') |
    (equity_complete['Indicator Name'] =='Mean height in meters, female, (age 15-49)') | 
    (equity_complete['Indicator Name'] =='Mean height in meters, male (age 18+)') |
    (equity_complete['Indicator Name'] =='Mean household per capita out-of-pocket health spending ($ 2011 PPP)') |
    (equity_complete['Indicator Name'] =='Mean share of household consumption or income used on out-of-pocket health spending (%)') |
    (equity_complete['Indicator Name'] =='Mean systolic blood pressure, adult population (mmHg)') |
    (equity_complete['Indicator Name'] =='Mortality rate, infant (per 1,000 live births)') |
    (equity_complete['Indicator Name'] =='Mortality rate, under-5 (per 1,000)') |
    (equity_complete['Indicator Name'] =='Pap smear in last 5 years (% of females 30-49)') |
    (equity_complete['Indicator Name'] =='Pregnant women receiving prenatal care of at least four visits (% of pregnant women)') |
    (equity_complete['Indicator Name'] =='Prevalence of HIV, total (% of population ages 15-49)') |
    (equity_complete['Indicator Name'] =='Prevalence of obesity, BMI > 30 (% of population 18+)') |
    (equity_complete['Indicator Name'] =='Prevalence of obesity, female, BMI > 30 (% of population 15-49)') |
    (equity_complete['Indicator Name'] =='Prevalence of obesity, female, BMI > 30 (% of population 18+)') |
    (equity_complete['Indicator Name'] =='Prevalence of obesity, male, BMI > 30 (% of population 18+)') |
    (equity_complete['Indicator Name'] =='Prevalence of overweight, BMI > 25 (% of population 18+)') |
    (equity_complete['Indicator Name'] =='Prevalence of overweight, female, BMI > 25 (% of population 18+)') |
    (equity_complete['Indicator Name'] =='Prevalence of overweight, female, BMI > 25 (% of population ages 15-49)') |
    (equity_complete['Indicator Name'] =='Prevalence of overweight, male, BMI > 25 (% of population 18+)') |
    (equity_complete['Indicator Name'] =='Prevalence of stunting, height for age (% of children under 5)') |
    (equity_complete['Indicator Name'] =='Prevalence of underweight, weight for age (% of children under 5)') | 
    (equity_complete['Indicator Name'] =='Proportion of population pushed below the $1.90 ($ 2011 PPP) poverty line by out-of-pocket health care expenditure (%)') |
    (equity_complete['Indicator Name'] =='Proportion of population pushed below the $21.70 ($ 2011 PPP) poverty line by out-of-pocket health care expenditure (%)') | 
    (equity_complete['Indicator Name'] =='Proportion of population pushed below the $3.20 ($ 2011 PPP) poverty line by out-of-pocket health care expenditure (%)') |
    (equity_complete['Indicator Name'] =='Proportion of population pushed below the $5.50 ($ 2011 PPP) poverty line by out-of-pocket health care expenditure (%)') |
    (equity_complete['Indicator Name'] =='Proportion of population pushed below the 60% median consumption poverty line by out-of-pocket health care expenditure (%)') | 
    (equity_complete['Indicator Name'] =='Proportion of population pushed by out-of-pocket health care expenditure below the societal poverty line, defined as the higher of the $1.90 ($ 2011 PPP) poverty line and a 50% of median consumption poverty line (%)') | 
    (equity_complete['Indicator Name'] =='Proportion of population spending more than 10% of household consumption or income on out-of-pocket health care expenditure (%)')|
    (equity_complete['Indicator Name'] =='Proportion of population spending more than 25% of household consumption or income on out-of-pocket health care expenditure (%)') |
    (equity_complete['Indicator Name'] =='Treated for high blood pressure (% of adult population)') |
    (equity_complete['Indicator Name'] =='Treated for raised blood glucose or diabetes (% of adult population)') |
    (equity_complete['Indicator Name'] =='Unmet need for contraception (% of females ages 15-49)') |
    (equity_complete['Indicator Name'] =='Use of insecticide-treated bed nets (% of under-5 population)')]

In [31]:
equity

,Country Name,Country Code,Indicator Name,Indicator Code,1982,1983,1984,1985,1986,1987,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,Afghanistan,AFG,Acute respiratory infections treated (% of chi...,HF.STA.ARIC.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,60.355908,NaN,NaN,NaN,NaN,61.427754,NaN,NaN,NaN
6,Afghanistan,AFG,Births attended by skilled health staff (% of ...,HF.STA.BRTC.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,39.496449,NaN,NaN,NaN,NaN,56.935620,NaN,NaN,NaN
12,Afghanistan,AFG,Blood pressure measured in last 12 months (% o...,HF.STA.BP18.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Afghanistan,AFG,Blood sugar measured in last 5 years (% of pop...,HF.STA.BLSG.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Afghanistan,AFG,Cholesterol measured in last five years (% of ...,HF.STA.CHOM.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62025,Zimbabwe,ZWE,Proportion of population spending more than 25...,HF.UHC.OOPC.25.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62031,Zimbabwe,ZWE,Treated for high blood pressure (% of adult po...,HF.STA.BPTR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62037,Zimbabwe,ZWE,Treated for raised blood glucose or diabetes (...,HF.STA.DIAB.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62043,Zimbabwe,ZWE,Unmet need for contraception (% of females age...,HF.UWT.TFRT,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.145692,NaN,NaN,NaN,NaN,0.104063,NaN,NaN,NaN
62049,Zimbabwe,ZWE,Use of insecticide-treated bed nets (% of unde...,HF.MLR.NETS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,9.919844,NaN,NaN,NaN,25.884485,8.881446,NaN,NaN,NaN

In [32]:
equity.columns

Index(['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code',
       '1982', '1983', '1984', '1985', '1986', '1987', '1988', '1989', '1990',
       '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999',
       '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008',
       '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017',
       '2018'],
      dtype='object')

In [33]:
equity = equity.drop(['Country Code', 'Indicator Code'], axis=1)

In [34]:
equity.head(5)

,Country Name,Indicator Name,1982,1983,1984,1985,1986,1987,1988,1989,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,Afghanistan,Acute respiratory infections treated (% of chi...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,60.355908,NaN,NaN,NaN,NaN,61.427754,NaN,NaN,NaN
6,Afghanistan,Births attended by skilled health staff (% of ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,39.496449,NaN,NaN,NaN,NaN,56.935620,NaN,NaN,NaN
12,Afghanistan,Blood pressure measured in last 12 months (% o...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Afghanistan,Blood sugar measured in last 5 years (% of pop...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Afghanistan,Cholesterol measured in last five years (% of ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [35]:
#use the melt and verticalize data 

equity_df = pd.melt(equity, id_vars=['Country Name','Indicator Name'])
equity_df = equity_df.rename(columns={'Country Name':'Country', 'Indicator Name':'parameter', 'variable':'Year', 'value':'value'})
equity_df

,Country,parameter,Year,value
0,Afghanistan,Acute respiratory infections treated (% of chi...,1982,NaN
1,Afghanistan,Births attended by skilled health staff (% of ...,1982,NaN
2,Afghanistan,Blood pressure measured in last 12 months (% o...,1982,NaN
3,Afghanistan,Blood sugar measured in last 5 years (% of pop...,1982,NaN
4,Afghanistan,Cholesterol measured in last five years (% of ...,1982,NaN
...,...,...,...,...
408179,Zimbabwe,Proportion of population spending more than 25...,2018,NaN
408180,Zimbabwe,Treated for high blood pressure (% of adult po...,2018,NaN
408181,Zimbabwe,Treated for raised blood glucose or diabetes (...,2018,NaN
408182,Zimbabwe,Unmet need for contraception (% of females age...,2018,NaN
408183,Zimbabwe,Use of insecticide-treated bed nets (% of unde...,2018,NaN

In [36]:
#######################

In [37]:
system_df.head(5)

       Country                               parameter  value  Year
0  Afghanistan  Health_expenditure_(percentage_of_GDP)   10.2  2016
1      Albania  Health_expenditure_(percentage_of_GDP)    6.7  2016
2      Algeria  Health_expenditure_(percentage_of_GDP)    6.6  2016
3      Andorra  Health_expenditure_(percentage_of_GDP)   10.4  2016
4       Angola  Health_expenditure_(percentage_of_GDP)    2.9  2016

In [38]:
efficiency_df.head(5)

  Country  Year Income group classification                 parameter    value
0  Angola  2006         Lower middle income  Life expectancy at birth  53.9271
1  Angola  2007         Lower middle income  Life expectancy at birth  55.0475
2  Angola  2008         Lower middle income  Life expectancy at birth  56.1393
3  Angola  2009         Lower middle income  Life expectancy at birth   57.181
4  Angola  2010         Lower middle income  Life expectancy at birth  58.1411

In [39]:
equity_df.head(5)

       Country                                          parameter  Year  value
0  Afghanistan  Acute respiratory infections treated (% of chi...  1982    NaN
1  Afghanistan  Births attended by skilled health staff (% of ...  1982    NaN
2  Afghanistan  Blood pressure measured in last 12 months (% o...  1982    NaN
3  Afghanistan  Blood sugar measured in last 5 years (% of pop...  1982    NaN
4  Afghanistan  Cholesterol measured in last five years (% of ...  1982    NaN

In [47]:
mytable = efficiency_df.groupby(['Country','Income group classification']).count()
mytable

                                                 Year  parameter  value
Country             Income group classification
Albania             Upper middle income           187        187    146
Algeria             Upper middle income           187        187    146
Angola              Lower middle income           187        187    140
Antigua and Barbuda High income                   187        187    135
Argentina           Upper middle income           187        187    146
...                                               ...        ...    ...
Venezuela, RB       Upper middle income           187        187    143
Vietnam             Lower middle income           187        187    146
Yemen, Rep.         Lower middle income           187        187    140
Zambia              Lower middle income           187        187    146
Zimbabwe            Low income                    187        187    146

[155 rows x 3 columns]

In [53]:
income_dict = {}

for row in range(len(efficiency_df.index)):
    country = efficiency_df.iloc[int(row)]['Country']
    income = efficiency_df.iloc[int(row)]['Income group classification']
    income_dict[country] = income
    
income_dict

{'Angola': 'Lower middle income',
 'Albania': 'Upper middle income',
 'United Arab Emirates': 'High income',
 'Argentina': 'Upper middle income',
 'Armenia': 'Lower middle income',
 'Antigua and Barbuda': 'High income',
 'Australia': 'High income',
 'Austria': 'High income',
 'Azerbaijan': 'Upper middle income',
 'Burundi': 'Low income',
 'Belgium': nan,
 'Benin': 'Low income',
 'Burkina Faso': 'Low income',
 'Bangladesh': 'Lower middle income',
 'Bulgaria': 'Upper middle income',
 'Bahrain': 'High income',
 'Bahamas, The': 'High income',
 'Bosnia & Herzegovina': nan,
 'Belarus': 'Upper middle income',
 'Belize': 'Upper middle income',
 'Bolivia': 'Lower middle income',
 'Brazil': 'Upper middle income',
 'Barbados': 'High income',
 'Brunei Darussalam': nan,
 'Bhutan': nan,
 'Botswana': 'Upper middle income',
 'Central African Republic': 'Low income',
 'Canada': 'High income',
 'Switzerland': 'High income',
 'Chile': 'High income',
 'China': 'Upper middle income',
 "Cote d'Ivoire": 'Lower middle income',
 'Cameroon': 'Lower middle income',
 'Congo, Rep.': 'Lower middle income',
 'Colombia': 'Upper middle income',
 'Comoros': 'Low income',
 'Cape Verde': 'Lower middle income',
 'Costa Rica': 'Upper middle income',
 'Cyprus': 'High income',
 'Czech Republic': 'High income',
 'Germany': 'High income',
 'Djibouti': 'Lower middle income',
 'Dominica': 'Upper middle income',
 'Denmark': 'High income',
 'Dominican Republic': 'Upper middle income',
 'Algeria': 'Upper middle income',
 'Ecuador': 'Upper middle income',
 'Egypt, Arab Rep.': 'Lower middle income',
 'Eritrea': 'Low income',
 'Spain': 'High income',
 'Estonia': 'High income',
 'Ethiopia': 'Low income',
 'Finland': 'High income',
 'Fiji': 'Upper middle income',
 'France': 'High income',
 'Gabon': 'Upper middle income',
 'United Kingdom': 'High income',
 'Georgia': 'Lower middle income',
 'Ghana': 'Lower middle income',
 'Guinea': 'Low income',
 'Gambia, The': 'Low income',
 'Guinea-Bissau': 'Low income',
 'Greece': 'High income',
 'Grenada': 'Upper middle income',
 'Guatemala': 'Lower middle income',
 'Guyana': 'Upper middle income',
 'China,P.R.:Hong Kong': nan,
 'Honduras': 'Lower middle income',
 'Croatia': 'Upper middle income',
 'Haiti': 'Low income',
 'Hungary': 'High income',
 'Indonesia': 'Lower middle income',
 'India': 'Lower middle income',
 'Ireland': nan,
 'Iran, Islamic Rep.': 'Upper middle income',
 'Iceland': 'High income',
 'Israel': nan,
 'Italy': 'High income',
 'Jamaica': 'Upper middle income',
 'Jordan': 'Lower middle income',
 'Japan': nan,
 'Kazakhstan': 'Upper middle income',
 'Kenya': 'Lower middle income',
 'Kyrgyz Republic': 'Lower middle income',
 'Cambodia': 'Lower middle income',
 'St. Kitts and Nevis': 'High income',
 'Korea, Rep.': 'Low income',
 'Kuwait': 'High income',
 'Lao PDR': 'Lower middle income',
 'Lebanon': 'Upper middle income',
 'Liberia': nan,
 'Libya': nan,
 'St. Lucia': 'Upper middle income',
 'Sri Lanka': 'Lower middle income',
 'Lesotho': 'Lower middle income',
 'Lithuania': 'High income',
 'Luxembourg': 'High income',
 'Latvia': 'High income',
 'Morocco': 'Lower middle income',
 'Moldova': 'Lower middle income',
 'Madagascar': 'Low income',
 'Mexico': 'Upper middle income',
 'Macedonia, FYR': 'Upper middle income',
 'Mali': 'Low income',
 'Malta': nan,
 'Myanmar': nan,
 'Montenegro, Rep. of': nan,
 'Mongolia': 'Lower middle income',
 'Mozambique': 'Low income',
 'Mauritania': 'Lower middle income',
 'Mauritius': 'Upper middle income',
 'Malawi': 'Low income',
 'Malaysia': 'Upper middle income',
 'Namibia': 'Upper middle income',
 'Niger': 'Low income',
 'Nigeria': 'Lower middle income',
 'Nicaragua': 'Lower middle income',
 'Netherlands': 'High income',
 'Norway': 'High income',
 'Nepal': 'Low income',
 'New Zealand': 'High income',
 'Oman': 'High income',
 'Pakistan': 'Lower middle income',
 'Panama': 'Upper middle income',
 'Peru': 'Upper middle income',
 'Philippines': 'Lower middle income',
 'Papua New Guinea': 'Lower middle income',
 'Poland': 'High income',
 'Puerto Rico': nan,
 'Portugal': nan,
 'Paraguay': 'Upper middle income',
 'Qatar': nan,
 'Romania': 'Upper middle income',
 'Russian Federation': 'Upper middle income',
 'Rwanda': 'Low income',
 'Saudi Arabia': 'High income',
 'Sudan': 'Lower middle income',
 'Senegal': 'Low income',
 'Singapore': nan,
 'Solomon Islands': 'Lower middle income',
 'Sierra Leone': 'Low income',
 'El Salvador': 'Lower middle income',
 'Serbia, Republic of': nan,
 'Suriname': nan,
 'Slovak Republic': 'High income',
 'Slovenia': 'High income',
 'Sweden': 'High income',
 'Swaziland': 'Lower middle income',
 'Seychelles': nan,
 'Syrian Arab Republic': 'Lower middle income',
 'Chad': 'Low income',
 'Togo': 'Low income',
 'Thailand': 'Upper middle income',
 'Tajikistan': 'Lower middle income',
 'Turkmenistan': 'Upper middle income',
 'Timor-Leste': nan,
 'Tonga': 'Upper middle income',
 'Trinidad and Tobago': 'High income',
 'Tunisia': 'Lower middle income',
 'Turkey': 'Upper middle income',
 'Tanzania': 'Low income',
 'Uganda': 'Low income',
 'Ukraine': 'Lower middle income',
 'Uruguay': 'High income',
 'United States': 'High income',
 'Uzbekistan': 'Lower middle income',
 'St. Vincent and the Grenadines': 'Upper middle income',
 'Venezuela, RB': 'Upper middle income',
 'Vietnam': 'Lower middle income',
 'Vanuatu': 'Lower middle income',
 'Samoa': 'Upper middle income',
 'Yemen, Rep.': 'Lower middle income',
 'South Africa': 'Upper middle income',
 'Congo, Dem. Rep.': 'Low income',
 'Zambia': 'Lower middle income',
 'Zimbabwe': 'Low income'}

In [59]:
system_df['Income group classification'] = [income_dict[x] if x in income_dict.keys() else 'No income group' for x in system_df['Country']] 
equity_df['Income group classification'] = [income_dict[x] if x in income_dict.keys() else 'No income group' for x in equity_df['Country']]

In [60]:
system_df

,Country,parameter,value,Year,Income group classification
0,Afghanistan,Health_expenditure_(percentage_of_GDP),10.2,2016,No income group
1,Albania,Health_expenditure_(percentage_of_GDP),6.7,2016,Upper middle income
2,Algeria,Health_expenditure_(percentage_of_GDP),6.6,2016,Upper middle income
3,Andorra,Health_expenditure_(percentage_of_GDP),10.4,2016,No income group
4,Angola,Health_expenditure_(percentage_of_GDP),2.9,2016,Lower middle income
...,...,...,...,...,...
1885,Virgin Islands (U.S.),Specialist_surgical_workforce_per_100000,NaN,2018,No income group
1886,West Bank and Gaza,Specialist_surgical_workforce_per_100000,NaN,2018,No income group
1887,"Yemen, Rep.",Specialist_surgical_workforce_per_100000,0.8,2018,Lower middle income
1888,Zambia,Specialist_surgical_workforce_per_100000,1.5,2018,Lower middle income
1889,Zimbabwe,Specialist_surgical_workforce_per_100000,1.6,2018,Low income

In [61]:
equity_df

,Country,parameter,Year,value,Income group classification
0,Afghanistan,Acute respiratory infections treated (% of chi...,1982,NaN,No income group
1,Afghanistan,Births attended by skilled health staff (% of ...,1982,NaN,No income group
2,Afghanistan,Blood pressure measured in last 12 months (% o...,1982,NaN,No income group
3,Afghanistan,Blood sugar measured in last 5 years (% of pop...,1982,NaN,No income group
4,Afghanistan,Cholesterol measured in last five years (% of ...,1982,NaN,No income group
...,...,...,...,...,...
408179,Zimbabwe,Proportion of population spending more than 25...,2018,NaN,Low income
408180,Zimbabwe,Treated for high blood pressure (% of adult po...,2018,NaN,Low income
408181,Zimbabwe,Treated for raised blood glucose or diabetes (...,2018,NaN,Low income
408182,Zimbabwe,Unmet need for contraception (% of females age...,2018,NaN,Low income
408183,Zimbabwe,Use of insecticide-treated bed nets (% of unde...,2018,NaN,Low income

In [62]:
efficiency_df

,Country,Year,Income group classification,parameter,value
0,Angola,2006,Lower middle income,Life expectancy at birth,53.9271
1,Angola,2007,Lower middle income,Life expectancy at birth,55.0475
2,Angola,2008,Lower middle income,Life expectancy at birth,56.1393
3,Angola,2009,Lower middle income,Life expectancy at birth,57.181
4,Angola,2010,Lower middle income,Life expectancy at birth,58.1411
...,...,...,...,...,...
32907,Zimbabwe,2012,Low income,"Health expenditure, public (% of government ex...",9.691281
32908,Zimbabwe,2013,Low income,"Health expenditure, public (% of government ex...",9.593592
32909,Zimbabwe,2014,Low income,"Health expenditure, public (% of government ex...",8.486653
32910,Zimbabwe,2015,Low income,"Health expenditure, public (% of government ex...",NaN
32911,Zimbabwe,2016,Low income,"Health expenditure, public (% of government ex...",NaN

In [64]:
frames = [system_df, efficiency_df, equity_df]

complete = pd.concat(frames)

complete

,Country,parameter,value,Year,Income group classification
0,Afghanistan,Health_expenditure_(percentage_of_GDP),10.2,2016,No income group
1,Albania,Health_expenditure_(percentage_of_GDP),6.7,2016,Upper middle income
2,Algeria,Health_expenditure_(percentage_of_GDP),6.6,2016,Upper middle income
3,Andorra,Health_expenditure_(percentage_of_GDP),10.4,2016,No income group
4,Angola,Health_expenditure_(percentage_of_GDP),2.9,2016,Lower middle income
...,...,...,...,...,...
408179,Zimbabwe,Proportion of population spending more than 25...,NaN,2018,Low income
408180,Zimbabwe,Treated for high blood pressure (% of adult po...,NaN,2018,Low income
408181,Zimbabwe,Treated for raised blood glucose or diabetes (...,NaN,2018,Low income
408182,Zimbabwe,Unmet need for contraception (% of females age...,NaN,2018,Low income
408183,Zimbabwe,Use of insecticide-treated bed nets (% of unde...,NaN,2018,Low income

In [65]:
complete.isnull().sum()

Country                             0
parameter                           0
value                          402722
Year                                0
Income group classification     37232
dtype: int64

In [66]:
complete = complete.dropna(subset=['Country', 'parameter','value'])

In [67]:
complete.isnull().sum()

Country                           0
parameter                         0
value                             0
Year                              0
Income group classification    1100
dtype: int64

In [68]:
complete = complete.dropna(subset=['Income group classification'])

In [69]:
complete['Year'].unique()

array(['2016', '2018', 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013,
       2014, 2015, 2016, '1982', '1983', '1984', '1985', '1986', '1987',
       '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995',
       '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003',
       '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011',
       '2012', '2013', '2014', '2015', '2017'], dtype=object)

In [70]:
complete = complete.replace({'Year': {2006: '2006',2007: '2007',
                                      2008: '2008',2009: '2009',
                                      2010: '2010',2011: '2011',
                                      2012: '2012',2013: '2013',
                                      2014: '2014',2015: '2015',
                                      2016: '2016'}})

In [71]:
complete['Year'].unique()

array(['2016', '2018', '2006', '2007', '2008', '2009', '2010', '2011',
       '2012', '2013', '2014', '2015', '1982', '1983', '1984', '1985',
       '1986', '1987', '1988', '1989', '1990', '1991', '1992', '1993',
       '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001',
       '2002', '2003', '2004', '2005', '2017'], dtype=object)

In [72]:
complete.to_excel("data_health.xlsx")